import { any, factErrors, factTypes, gitRepository, types } from "./policy-helpers.js";
export const protocolZones = [
  {
    source: "protocol/attempt.ts",
    allow: [
      any("git/admission.ts"),
      any("git/observe.ts"),
      any("git/private-state-seat.ts", ["PrivateStatePublicationSeat", "confirmPrivateStatePublication"]),
      types("git/read-observation.ts", ["GitDecodeChannel"]),
      any("git/repository.ts", ["GIT_REF", "GitRefAssertion", "readRefs"]),
      gitRepository,
      types("core/decide.ts"),
      any("core/facts/codec.ts"),
      factErrors,
      any("core/facts/fold.ts", ["foldJournal"]),
      types("core/facts/offer.ts"),
      factTypes,
    ],
  },
  {
    source: "protocol/run.ts",
    allow: [
      any("git/observe.ts"),
      any("git/private-state-seat.ts"),
      types("git/read-observation.ts"),
      types("git/repository.ts", ["GitRefAssertion"]),
      gitRepository,
      types("core/decide.ts"),
      types("core/facts/offer.ts"),
      types("core/facts/types.ts"),
      any("protocol/attempt.ts"),
    ],
  },
  {
    source: "protocol/outcome.ts",
    allow: [
      types("core/facts/types.ts"),
      types("git/reconcile.ts"),
      types("git/scratch.ts"),
      types("protocol/attempt.ts"),
      types("protocol/intent.ts"),
      types("protocol/run.ts"),
    ],
  },
  {
    source: "protocol/bind.ts",
    allow: [
      any("git/observe.ts"),
      any("git/identity.ts", ["gitObjectIdForSnapshot"]),
      types("git/read-observation.ts", ["GitDecodeChannel"]),
      any("git/repository.ts"),
      gitRepository,
      factTypes,
      any("core/verbs/bind.ts"),
      any("protocol/intent.ts"),
      any("protocol/outcome.ts"),
      types("protocol/run.ts"),
      types("verification/declaration.ts"),
    ],
  },
  {
    source: "protocol/intent.ts",
    allow: [
      any("git/observe.ts"),
      types("git/read-observation.ts", ["GitDecodeChannel", "GitTreeSelection"]),
      any("git/scratch.ts", ["materializeScratchCandidate", "WorktreeLeak"]),
      types("git/hooks.ts", ["HookFailure"]),
      any("settings.ts", ["projectSettings"]),
      types("git/repository.ts", ["GitRefAssertion"]),
      gitRepository,
      types("core/decide.ts"),
      types("core/facts/types.ts"),
      any("core/subject.ts", ["dependencyKeySet"]),
      any("core/verbs/attestation.ts"),
      any("protocol/attempt.ts", ["mintAttempts"]),
      any("protocol/run.ts"),
      any("verification/execution.ts"),
      any("verification/declaration.ts", ["VERIFIED", "VerificationDefinition"]),
      any("core/facts/gate.ts", ["latestCurrentAttestations"]),
    ],
  },
  {
    source: "protocol/placement.ts",
    allow: [
      any("coordination/sqlite-transaction-lock.ts", ["SqliteTransactionLockError"]),
      any("core/facts/errors.ts", ["AuthorityCorruptionError"]),
      any("core/facts/observation.ts", ["contractState"]),
      types("core/facts/types.ts"),
      any("core/verbs/placement.ts"),
      any("git/observe.ts", ["observeGitForAdmissionAt"]),
      any("git/private-state-seat.ts"),
      types("git/read-observation.ts", ["GitDecodeChannel"]),
      any("git/reconcile.ts", ["ReconcileResult", "reconcileEffectFailure"]),
      any("git/process.ts", ["GitPlumbingError", "GitRepository"]),
      any("git/target-placement.ts"),
      any("protocol/attempt.ts", ["AcceptedAdmission", "admitDecidedOffer", "mintAttempts"]),
      any("protocol/run.ts"),
    ],
  },
  {
    source: "protocol/operations.ts",
    allow: [
      any("git/integration.ts", ["readDeliveryDiff"]),
      types("git/integration.ts", ["IntegrationPreparationRefusal"]),
      types("git/tender.ts", ["DirtyWorkspaceRefusal"]),
      any("git/observe.ts", ["currentBranch", "observeContractAt"]),
      any("git/read-observation.ts", ["GitDecodeChannel", "withGitReadObservation"]),
      any("git/repository.ts"),
      gitRepository,
      types("git/scratch.ts", ["WorktreeLeak"]),
      types("git/target-placement.ts", ["TargetPlacementRefusal"]),
      types("core/facts/types.ts"),
      types("core/verbs/abandon.ts"),
      types("core/verbs/amend.ts"),
      types("core/verbs/arc.ts"),
      types("core/verbs/bind.ts"),
      types("core/verbs/deliver.ts"),
      types("core/verbs/placement.ts"),
      types("core/verbs/attestation.ts"),
      types("protocol/attempt.ts"),
      types("protocol/bind.ts"),
      types("protocol/intent.ts"),
      types("protocol/outcome.ts"),
      types("protocol/placement.ts"),
      any("protocol/read/documents.ts"),
      any("protocol/read/status.ts"),
      types("protocol/run.ts"),
      types("verification/declaration.ts"),
    ],
  },
  {
    source: "protocol/amend.ts",
    allow: [
      any("git/observe.ts", ["extendContractsForAdmissionAt", "observeContractsForAdmissionAt"]),
      any("git/private-state-seat.ts"),
      types("git/observe.ts", ["GitDecisionObservation"]),
      types("git/read-observation.ts", ["GitDecodeChannel"]),
      any("core/facts/observation.ts", ["contractState"]),
      types("core/facts/types.ts", ["AmendData", "ContractId", "ContractTerms"]),
      any("core/verbs/amend.ts", ["AmendInput", "AmendRefusal", "decideAmend"]),
      types("verification/declaration.ts", ["VerificationDeclarationPreparation", "VerificationDeclarationRefusal"]),
      any("protocol/attempt.ts", ["admitDecidedOffer", "mintAttempts"]),
      any("protocol/outcome.ts", ["admitted"]),
      types("protocol/operations.ts", ["MutationOperationInput", "IntentOutcome"]),
      any("protocol/operations.ts", ["timestamp"]),
    ],
  },
  {
    source: "protocol/completion.ts",
    allow: [
      types("core/facts/types.ts", ["ActorId", "ContractId", "SnapshotId"]),
      types("git/scratch.ts", ["WorktreeLeak"]),
      gitRepository,
      types("git/read-observation.ts", ["GitDecodeChannel"]),
      types("verification/declaration.ts", ["VerificationDeclarationPreparation"]),
      any("protocol/intent.ts"),
      any("protocol/placement.ts", ["admitPlacement"]),
      any("protocol/reintegrate.ts"),
      types("protocol/outcome.ts", ["AcceptedProtocolStep"]),
      types("protocol/operations.ts", ["PlacementStop", "VerificationStop"]),
      any("protocol/operations.ts", ["mergeAdmissions", "placementStop", "timestamp", "unpackVerificationOutcome"]),
    ],
  },
  {
    source: "protocol/reintegrate.ts",
    allow: [
      any("core/facts/observation.ts", ["contractState"]),
      types("core/facts/types.ts", ["ActorId", "ContractId", "ReintegratedData"]),
      any("core/verbs/reintegrate.ts"),
      any("git/integration.ts"),
      any("git/observe.ts", ["observeContractsForAdmissionAt"]),
      any("git/private-state-seat.ts"),
      gitRepository,
      types("git/read-observation.ts", ["GitDecodeChannel"]),
      types("git/repository.ts", ["GitRefAssertion"]),
      any("protocol/attempt.ts"),
      any("protocol/operations.ts", ["timestamp"]),
      types("protocol/run.ts", ["ProtocolTerminal"]),
      any("protocol/placement.ts"),
    ],
  },
  {
    source: "protocol/deliver.ts",
    allow: [
      any("git/private-state-seat.ts"),
      any("git/integration.ts", [
        "materializeIntegrationSnapshot",
        "materializeJudgedConflict",
        "planIntegration",
        "workspaceMergeStatePresent",
        "worktreeChangeId",
      ]),
      any("git/workspace.ts", ["worktreePath"]),
      any("git/tender.ts", [
        "captureTender",
        "dirtyTenderRefusal",
        "materializeTenderSnapshot",
        "prepareDeliveryCommitMetadata",
      ]),
      any("git/observe.ts", ["currentBranch", "observeContractsForAdmissionAt"]),
      gitRepository,
      types("core/decide.ts", ["AttemptContext"]),
      any("core/facts/observation.ts", ["contractState"]),
      types("core/facts/types.ts", [
        "ActorId",
        "ContractId",
        "ContractState",
        "DeliverData",
        "JournalEntry",
        "SnapshotId",
      ]),
      any("core/verbs/deliver.ts", ["DeliverInput", "DeliverRefusal", "decideDeliver"]),
      types("verification/declaration.ts", ["VerificationDeclarationRefusal"]),
      types("protocol/intent.ts", ["CurrentVerifiedAttestation"]),
      any("protocol/completion.ts"),
      any("protocol/attempt.ts", ["admitDecidedOffer", "mintAttempts"]),
      any("protocol/outcome.ts", ["admitted"]),
      any("workspace-place.ts", ["ManagedWorktreeAppointment", "appointmentFor", "readPlaceRegister"]),
      types("protocol/operations.ts", [
        "AttemptDecision",
        "DeliverConflictRefusal",
        "DeliveryPreparationRefusal",
        "DocumentDerivation",
        "IntentOutcome",
        "IntentRefusal",
        "MutationOperationInput",
      ]),
      any("protocol/operations.ts", ["timestamp"]),
    ],
  },
  {
    source: "protocol/review.ts",
    allow: [
      any("git/private-state-seat.ts"),
      any("git/integration.ts", ["worktreeChangeId"]),
      any("git/tender.ts", [
        "TenderCapture",
        "WorkspaceDirtyDelta",
        "captureTender",
        "dirtyTenderDelta",
        "dirtyTenderRefusal",
      ]),
      types("git/tender.ts", ["DirtyWorkspaceRefusal"]),
      any("git/observe.ts", ["observeContractsForAdmissionAt"]),
      any("core/subject.ts", ["dependencyKeySet"]),
      types("core/decide.ts", ["AttemptContext"]),
      any("core/facts/observation.ts", ["contractState"]),
      any("core/facts/types.ts", ["gate"]),
      types("core/facts/types.ts", ["AttestationData", "ContractId", "ContractState", "DeliverData"]),
      any("core/verbs/attestation.ts", ["AttestationInput", "AttestationRefusal", "decideAttestation"]),
      any("protocol/attempt.ts", ["admitDecidedOffer", "mintAttempts"]),
      any("protocol/outcome.ts", ["admitted"]),
      any("protocol/completion.ts"),
      any("workspace-place.ts", ["appointmentFor", "readPlaceRegister"]),
      types("protocol/operations.ts", [
        "AttemptDecision",
        "DocumentDerivation",
        "IntentOutcome",
        "MutationOperationInput",
        "RepositoryScope",
      ]),
      any("protocol/operations.ts", ["timestamp"]),
    ],
  },
  {
    source: "protocol/audit.ts",
    allow: [
      any("git/integration.ts", ["DeliveryDiffScope", "readDeliveryDiff", "readDeliveryScope"]),
      any("git/observe.ts", ["observeContractsForAdmissionAt"]),
      any("git/target-placement.ts", ["AuditTargetAnswer", "adjudicateAuditTarget"]),
      any("core/facts/observation.ts", ["activeContract", "documentIsCurrent"]),
      types("core/facts/types.ts", ["ChangeId", "ContractState", "DeliverData", "SnapshotId"]),
      any("workspace-place.ts", ["ManagedWorktreeAppointment", "readManagedWorktreeAppointment"]),
      any("protocol/intent.ts", ["verifyDelivery"]),
      any("protocol/outcome.ts", ["accepted", "admitted"]),
      types("protocol/operations.ts", [
        "DeliveryPreparationRefusal",
        "DocumentDerivation",
        "IntentOutcome",
        "MutationOperationInput",
        "RepositoryScope",
        "VerificationStop",
      ]),
      any("protocol/operations.ts", ["timestamp", "unpackVerificationOutcome"]),
      any("protocol/deliver.ts", ["prepareDelivery"]),
    ],
  },
  {
    source: "protocol/abandon.ts",
    allow: [
      any("core/verbs/abandon.ts", ["AbandonRefusal", "decideAbandon"]),
      types("git/read-observation.ts", ["GitTreeSelection"]),
      any("protocol/intent.ts", ["admitIntent"]),
      any("protocol/outcome.ts", ["complete"]),
      types("protocol/run.ts", ["CompanionDecorator"]),
      types("protocol/operations.ts", ["IntentOutcome", "MutationOperationInput"]),
      any("protocol/operations.ts", ["timestamp"]),
    ],
  },
  {
    source: "protocol/arc.ts",
    allow: [
      types("core/facts/types.ts", ["ArcData"]),
      any("core/verbs/arc.ts", ["ArcRefusal", "decideArc"]),
      any("protocol/intent.ts", ["admitIntent"]),
      any("protocol/outcome.ts", ["complete"]),
      types("protocol/operations.ts", ["IntentOutcome", "MutationOperationInput"]),
      any("protocol/operations.ts", ["timestamp"]),
    ],
  },
  {
    source: "protocol/reconcile.ts",
    allow: [
      any("git/reconcile.ts", ["ReconcileResult", "reconcile", "reconcileBatch", "reconcileObservationFailure"]),
      any("git/observe.ts", ["observeContractWorld"]),
      any("git/read-observation.ts", ["withGitReadObservation"]),
      types("git/read-observation.ts", ["GitDecodeChannel"]),
      any("core/facts/errors.ts", ["AuthorityCorruptionError"]),
      types("core/facts/types.ts", ["ContractId", "ContractState"]),
      types("git/hooks.ts", ["WorktreeHooks"]),
      types("protocol/operations.ts", ["MutationOperationInput", "RepositoryScope"]),
    ],
  },
  {
    source: "protocol/read/observation.ts",
    allow: [
      any("git/hooks.ts", ["observeWorktreeHookMarker"]),
      types("git/process.ts", ["GitRepository"]),
      any("git/repository.ts", ["registeredWorktrees", "worktreeGitDirectory"]),
      any("git/target-placement.ts", ["observeTargetCheckoutShape"]),
      types("protocol/read/status.ts", ["ContractRow"]),
    ],
  },
  {
    source: "protocol/read/status.ts",
    allow: [
      any("git/observe.ts"),
      any("git/read-observation.ts", ["GitDecodeChannel", "GitReadObservation", "withGitReadObservation"]),
      gitRepository,
      any("git/workspace.ts", ["worktreePath", "observeTargetLag", "observeWorkspace"]),
      any("workspace-place.ts", ["PlaceRegister", "appointmentFor", "readPlaceRegister"]),
      types("git/workspace.ts", ["ContractTargetLag", "ContractWorkspaceObservation"]),
      any("body/decode.ts", ["decodeContractDocument"]),
      any("core/facts/gate.ts", ["GateCurrent", "gateReports"]),
      any("core/facts/observation.ts", ["prerequisiteStatus"]),
      any("core/facts/types.ts", ["ContractId", "ContractState", "SnapshotId"]),
      types("core/facts/types.ts"),
      types("protocol/read/status.ts", ["ContractRow"]),
    ],
  },
  {
    source: "protocol/read/documents.ts",
    allow: [
      any("git/observe.ts", ["observeActiveContractWorld"]),
      types("git/read-observation.ts", ["GitReadObservation"]),
      types("core/facts/types.ts", ["ContractId"]),
    ],
  },
];
