import type { ArchitecturePolicy } from "./engine.js";

const any = (target: string, symbols?: readonly string[]) => symbols ? { target, symbols } : { target };
const types = (target: string) => ({ target, mode: "type-only" as const });

export const KEIYAKU_ARCHITECTURE_POLICY = {
  zones: [
    { source: "core/facts/types.ts", allow: [] },
    { source: "core/facts/codec.ts", allow: [any("core/facts/types.ts"), any("core/subject.ts", ["parseSubjectKey"])] },
    {
      source: "core/facts/fold.ts",
      allow: [
        any("core/facts/eligibility.ts", ["samePrerequisites"]),
        any("core/facts/gate.ts"),
        any("core/facts/types.ts"),
      ],
    },
    { source: "core/facts/gate.ts", allow: [any("core/subject.ts"), any("core/facts/types.ts")] },
    { source: "core/declaration-key.ts", allow: [] },
    { source: "core/subject.ts", allow: [any("core/declaration-key.ts"), any("core/facts/types.ts")] },
    { source: "core/facts/eligibility.ts", allow: [any("core/facts/offer.ts"), any("core/facts/types.ts")] },
    { source: "core/facts/offer.ts", allow: [any("core/facts/types.ts")] },
    { source: "core/facts/observation.ts", allow: [any("core/facts/types.ts")] },
    {
      source: "core/decide.ts",
      allow: [any("core/facts/observation.ts"), any("core/facts/offer.ts"), any("core/facts/types.ts")],
    },
    {
      source: "core/verbs/**",
      allow: [
        types("core/decide.ts"),
        any("core/subject.ts", ["currentSubject"]),
        any("core/facts/eligibility.ts", ["samePrerequisites"]),
        any("core/facts/gate.ts"),
        any("core/facts/types.ts"),
      ],
    },
    { source: "carrier/identity.ts", allow: [any("core/facts/types.ts")] },
    { source: "carrier/repository.ts", allow: [any("carrier/identity.ts")] },
    {
      source: "carrier/admission.ts",
      allow: [
        any("carrier/identity.ts"),
        any("carrier/repository.ts"),
        any("core/facts/codec.ts"),
        any("core/facts/fold.ts"),
        any("core/facts/offer.ts"),
        any("core/facts/types.ts"),
      ],
    },
    {
      source: "carrier/observe.ts",
      allow: [
        any("carrier/identity.ts"),
        any("carrier/repository.ts"),
        any("core/facts/codec.ts"),
        any("core/facts/fold.ts"),
        any("core/facts/observation.ts"),
        any("core/facts/types.ts"),
      ],
    },
    {
      source: "carrier/delivery.ts",
      allow: [
        any("carrier/identity.ts"),
        any("carrier/observe.ts"),
        any("carrier/reconcile.ts"),
        any("carrier/repository.ts"),
        any("core/facts/types.ts"),
      ],
    },
    {
      source: "carrier/reconcile.ts",
      allow: [any("carrier/identity.ts"), any("carrier/repository.ts"), any("core/facts/types.ts")],
    },
    {
      source: "carrier/verification.ts",
      allow: [any("carrier/identity.ts"), any("carrier/repository.ts"), any("core/facts/types.ts")],
    },
    {
      source: "protocol/attempt.ts",
      allow: [
        any("core/facts/codec.ts"),
        any("core/facts/observation.ts"),
        any("core/facts/offer.ts"),
        any("core/facts/types.ts"),
      ],
    },
    {
      source: "protocol/run.ts",
      allow: [
        any("carrier/admission.ts"),
        any("carrier/observe.ts"),
        any("carrier/repository.ts", ["GitPlumbingError", "GitRepository"]),
        any("core/decide.ts"),
        any("core/facts/observation.ts"),
        any("core/facts/offer.ts"),
        any("core/facts/types.ts"),
        any("protocol/attempt.ts"),
      ],
    },
    {
      source: "protocol/intent.ts",
      allow: [
        types("carrier/delivery.ts"),
        any("carrier/observe.ts"),
        any("carrier/verification.ts", ["prepareStoredVerification"]),
        types("carrier/repository.ts"),
        types("core/decide.ts"),
        any("core/facts/gate.ts"),
        any("core/facts/eligibility.ts"),
        any("core/facts/types.ts"),
        any("core/subject.ts", ["currentSubject"]),
        any("core/verbs/placement.ts"),
        any("core/verbs/attestation.ts"),
        any("protocol/run.ts"),
        any("verification/producer.ts"),
      ],
    },
    {
      source: "protocol/operations.ts",
      allow: [
        any("carrier/delivery.ts"),
        any("carrier/identity.ts"),
        any("carrier/observe.ts"),
        any("carrier/reconcile.ts"),
        any("carrier/repository.ts"),
        any("carrier/verification.ts", ["readDeliveryDiff"]),
        any("core/facts/fold.ts"),
        types("core/facts/types.ts"),
        any("core/subject.ts", ["currentSubject"]),
        any("core/verbs/abandon.ts"),
        any("core/verbs/amend.ts"),
        any("core/verbs/arc.ts"),
        any("core/verbs/bind.ts"),
        any("core/verbs/deliver.ts"),
        types("core/verbs/placement.ts"),
        any("core/verbs/attestation.ts"),
        any("protocol/intent.ts"),
        any("protocol/read/audit.ts"),
        any("protocol/read/status.ts"),
        types("protocol/run.ts"),
        any("verification/producer.ts"),
      ],
    },
    {
      source: "protocol/read/**",
      allow: [
        any("carrier/observe.ts"),
        any("carrier/reconcile.ts", ["deliveryWorktreePath"]),
        types("carrier/repository.ts"),
        any("core/facts/types.ts"),
      ],
    },
    { source: "runtime/proc/**", allow: [] },
    { source: "verification/plan.ts", allow: [types("core/facts/types.ts")] },
    {
      source: "verification/producer.ts",
      allow: [
        types("core/facts/types.ts"),
        any("runtime/proc/run.ts"),
        any("verification/plan.ts"),
      ],
    },
    {
      source: "library/keiyaku.ts",
      allow: [
        any("body/**"),
        any("core/facts/codec.ts"),
        any("core/facts/gate.ts", ["effectiveGates"]),
        any("core/facts/types.ts"),
        any("protocol/operations.ts"),
      ],
    },
    { source: "library/**", allow: [] },
    {
      source: "index.ts",
      allow: [any("library/**")],
    },
    { source: "markdown/**", allow: [any("markdown/**")] },
    {
      source: "body/**",
      allow: [
        any("body/**"),
        any("markdown/**"),
        any("core/facts/types.ts"),
        any("core/facts/codec.ts"),
      ],
    },
    { source: "cli/**", allow: [any("index.ts"), any("cli/**")] },
    { source: "scripts/architecture/**", allow: [any("scripts/architecture/**")] },
    { source: "scripts/check-architecture.ts", allow: [any("scripts/architecture/**")] },
    { source: "scripts/model-impact/**", allow: [any("scripts/model-impact/**")] },
    { source: "scripts/model-change-impact.ts", allow: [any("scripts/model-impact/**")] },
  ],
  sensitiveImports: [
    { module: "node:module", owners: [] },
    { module: "module", owners: [] },
    {
      module: "node:child_process",
      owners: [
        { source: "carrier/repository.ts", symbols: ["execFileSync"] },
        { source: "runtime/proc/**", symbols: ["spawn"] },
        { source: "scripts/model-change-impact.ts", symbols: ["execFileSync"] },
      ],
    },
    { module: "child_process", owners: [] },
    {
      module: "node:fs",
      owners: [
        { source: "scripts/check-architecture.ts", symbols: ["readFileSync", "readdirSync"] },
        { source: "scripts/model-change-impact.ts", symbols: ["readFileSync", "readdirSync"] },
        { source: "cli/invoke.ts", symbols: ["readFileSync"] },
        { source: "cli/settings.ts", symbols: ["readFileSync"] },
        { source: "carrier/reconcile.ts", symbols: ["existsSync", "mkdirSync", "realpathSync"] },
      ],
    },
    { module: "fs", owners: [] },
    { module: "node:fs/promises", owners: [] },
    { module: "fs/promises", owners: [] },
    {
      module: "node:crypto",
      owners: [
        { source: "carrier/verification.ts", symbols: ["randomBytes"] },
        { source: "carrier/identity.ts", symbols: ["randomBytes"] },
        { source: "protocol/intent.ts", symbols: ["randomBytes"] },
        { source: "core/declaration-key.ts", symbols: ["createHash"] },
      ],
    },
    { module: "crypto", owners: [] },
  ],
  forbiddenModules: [
    "better-sqlite3",
    "sqlite3",
    "node:sqlite",
  ],
  capabilityRules: [
    { capability: "dynamic-import-nonliteral", owners: [] },
    { capability: "eval", owners: [] },
    { capability: "function-constructor", owners: [] },
    { capability: "math-random", owners: [] },
    { capability: "module-mutable-state", owners: [] },
    { capability: "date-now", owners: ["carrier/identity.ts", "protocol/intent.ts"] },
    { capability: "new-date-current", owners: ["protocol/operations.ts"] },
    { capability: "process-argv", owners: ["cli/main.ts", "cli/index.ts", "scripts/check-architecture.ts", "scripts/model-change-impact.ts"] },
    { capability: "process-cwd", owners: ["carrier/repository.ts", "library/keiyaku.ts", "scripts/check-architecture.ts", "scripts/model-change-impact.ts"] },
    { capability: "process-environment", owners: ["cli/invoke.ts", "carrier/repository.ts", "protocol/operations.ts"] },
    { capability: "process-output", owners: ["cli/main.ts", "cli/index.ts", "scripts/check-architecture.ts", "scripts/model-change-impact.ts"] },
    { capability: "process-pid", owners: [] },
    { capability: "require", owners: [] },
  ],
  forbiddenFileNames: [
    "approval-preparation.ts",
    "claim.ts",
    "forfeit.ts",
    "open.ts",
    "petition-preparation.ts",
    "petition.ts",
    "pipeline.ts",
    "renew.ts",
    "seal.ts",
  ],
  forbiddenDeclarations: [
    /(?:Open|Seal|Renew|Petition|Claim|Forfeit)(?:Data|Entry|Input|Refusal|Decision|Offer|State|Result)$/,
  ],
  verbDirectory: "core/verbs/",
} as const satisfies ArchitecturePolicy;
