import { any, factErrors, factTypes, gitRepository, types } from "./policy-helpers.js";
export const gitZones = [
  { source: "git/identity.ts", allow: [factTypes] },
  { source: "git/tree.ts", allow: [any("git/identity.ts")] },
  {
    source: "git/process.ts",
    allow: [any("runtime/proc/run.ts", ["consumeProcessStdout", "spawnCancellableProcess"])],
  },
  {
    source: "git/repository.ts",
    allow: [
      any("git/identity.ts"),
      any("git/tree.ts"),
      factErrors,
      any("git/process.ts", ["GitPlumbingError", "runGit", "runGitWithEnvironment", "GitRepository"]),
    ],
  },
  {
    source: "git/read-observation.ts",
    allow: [
      factErrors,
      any("git/identity.ts"),
      any("git/process.ts", ["GitPlumbingError", "GitRepository"]),
      any("runtime/proc/run.ts", ["spawnCancellableProcess"]),
      any("git/repository.ts"),
      any("git/tree.ts", ["parseTreeObject", "TreeEntry", "validPath"]),
    ],
  },
  {
    source: "git/admission.ts",
    allow: [
      any("git/identity.ts"),
      types("git/observe.ts"),
      gitRepository,
      any("git/repository.ts"),
      any("git/tree.ts", ["validPath"]),
      any("core/facts/codec.ts"),
      types("core/facts/offer.ts"),
      types("core/facts/types.ts"),
    ],
  },
  {
    source: "git/observe.ts",
    allow: [
      any("git/identity.ts"),
      any("git/read-observation.ts", [
        "GitBlobResult",
        "GitDecodeChannel",
        "GitReadObservation",
        "GitTreeSelection",
        "readGitTreeSelection",
        "withGitReadObservation",
        "withGitTargetedReadObservation",
      ]),
      any("git/repository.ts"),
      any("git/process.ts", ["GitPlumbingError", "runGit", "GitRepository"]),
      factErrors,
      any("core/facts/codec.ts"),
      any("core/facts/fold.ts"),
      types("core/facts/observation.ts"),
      types("core/facts/types.ts"),
    ],
  },
  {
    source: "git/tender.ts",
    allow: [
      any("git/identity.ts"),
      any("git/repository.ts"),
      any("git/process.ts", ["GitPlumbingError", "runGit", "runGitWithEnvironment", "GitRepository"]),
      any("git/workspace.ts", ["captureWorkspaceTree", "unmergedWorkspacePaths", "workspaceMergeHead", "worktreePath"]),
      types("core/decide.ts"),
      types("core/facts/types.ts"),
    ],
  },
  {
    source: "git/integration.ts",
    allow: [
      any("git/identity.ts"),
      any("git/repository.ts"),
      any("git/process.ts", ["GitPlumbingError", "runGit", "runGitWithEnvironment", "GitRepository"]),
      any("git/workspace.ts", ["workspaceMergeStatePresent"]),
      types("git/tender.ts"),
      factErrors,
      types("core/decide.ts"),
      types("core/facts/types.ts"),
    ],
  },
  {
    source: "git/workspace.ts",
    allow: [
      types("core/facts/types.ts"),
      any("git/identity.ts"),
      any("git/process.ts", ["GitPlumbingError", "runGit", "runGitWithEnvironment", "GitRepository"]),
      any("git/repository.ts"),
      types("world.ts"),
    ],
  },
  {
    source: "git/nuke.ts",
    allow: [
      any("contract-worktree.ts", ["nukeContractWorktreeLock"]),
      types("core/facts/types.ts", ["ContractId"]),
      any("git/hooks.ts", ["nukeWorktreeHookResidue"]),
      any("git/process.ts", ["runGit", "GitRepository"]),
      any("git/repository.ts", [
        "CANDIDATE_PIN_REF_NAMESPACE",
        "DELIVERY_REF_NAMESPACE",
        "GIT_REF",
        "MIGRATION_CANDIDATE_PIN_REF_NAMESPACE",
        "MIGRATION_DELIVERY_REF_NAMESPACE",
        "NoGitWorldError",
        "readRef",
        "registeredWorktrees",
        "repositoryAt",
        "worktreeGitDirectory",
      ]),
      any("git/workspace.ts", ["worktreePath"]),
      any("workspace-place.ts", ["nukeEmptyPlaceAuthority", "readPlaceRegister", "releaseManagedWorktrees"]),
      types("world.ts", ["WorldRoot"]),
    ],
  },
  {
    source: "git/target-placement.ts",
    allow: [
      any("coordination/sqlite-transaction-lock.ts"),
      types("core/facts/offer.ts"),
      types("core/facts/types.ts"),
      any("git/identity.ts"),
      any("git/observe.ts", ["currentBranch"]),
      any("git/process.ts", ["consumeGitStdout", "GitPlumbingError", "runGit", "GitRepository"]),
      any("git/repository.ts"),
      any("git/workspace.ts", ["captureWorkspaceTree"]),
    ],
  },
  {
    source: "git/reconcile.ts",
    allow: [
      any("coordination/sqlite-transaction-lock.ts"),
      factErrors,
      types("core/facts/types.ts"),
      any("git/hooks.ts"),
      any("git/identity.ts"),
      any("git/observe.ts"),
      types("git/read-observation.ts", ["GitDecodeChannel"]),
      any("git/read-observation.ts", ["withGitDecodeChannel"]),
      any("git/process.ts", ["GitPlumbingError", "runGit", "GitRepository"]),
      any("git/repository.ts"),
      any("git/target-placement.ts"),
      any("git/terminal-seal.ts"),
      any("git/terminal-reconcile.ts"),
      any("git/workspace.ts", ["followManagedWorktree", "followDependentManagedWorktree", "worktreePath"]),
      any("git/scratch.ts", ["removeCollectableScratchWorktrees"]),
    ],
  },
  {
    source: "git/terminal-reconcile.ts",
    allow: [
      types("core/facts/types.ts"),
      any("git/hooks.ts", ["runDestroyHooks", "WorktreeHooks"]),
      any("git/identity.ts"),
      any("git/process.ts", ["GitPlumbingError", "runGit", "GitRepository"]),
      types("git/read-observation.ts", ["GitDecodeChannel"]),
      types("git/reconcile.ts", [
        "Effect",
        "ReconcileAccumulation",
        "ReconcileLag",
        "ReconcileResult",
        "WorktreeTopology",
      ]),
      any("git/repository.ts"),
      any("git/terminal-seal.ts"),
      any("git/workspace.ts", ["worktreePath"]),
    ],
  },
  {
    source: "workspace-place.ts",
    allow: [
      any("coordination/durable-file.ts", ["replaceFileDurably"]),
      any("coordination/sqlite-transaction-lock.ts"),
      any("core/facts/errors.ts", ["AuthorityCorruptionError"]),
      any("core/facts/types.ts", ["contractId", "ContractId"]),
      gitRepository,
      any("git/workspace.ts", ["worktreePath"]),
    ],
  },
  {
    source: "contract-worktree.ts",
    allow: [
      any("contract-guidance.ts", ["renderContractAppointment", "renderContractGuidance"]),
      any("coordination/durable-file.ts"),
      any("coordination/sqlite-transaction-lock.ts"),
      any("core/facts/errors.ts", ["AuthorityCorruptionError"]),
      factTypes,
      any("git/process.ts", ["GitPlumbingError", "runGit", "GitRepository"]),
      any("git/repository.ts"),
      any("git/workspace.ts", ["worktreePath"]),
      any("workspace-place.ts", ["appointmentFor", "placeRegisterPath", "readPlaceRegister", "PlaceRegister"]),
    ],
  },
  {
    source: "contract-guidance.ts",
    allow: [types("core/facts/types.ts", ["ArcData", "ContractId", "ContractState"])],
  },
  {
    source: "git/terminal-seal.ts",
    allow: [
      types("core/facts/types.ts"),
      any("git/identity.ts"),
      any("git/process.ts", ["runGit", "GitRepository"]),
      any("git/repository.ts"),
      any("git/workspace.ts", ["captureWorkspaceTree"]),
    ],
  },
  {
    source: "git/hooks.ts",
    allow: [
      any("coordination/durable-file.ts"),
      any("coordination/sqlite-transaction-lock.ts"),
      any("runtime/proc/run.ts"),
    ],
  },
  {
    source: "git/scratch.ts",
    allow: [
      any("coordination/sqlite-transaction-lock.ts"),
      any("git/identity.ts"),
      any("git/process.ts", ["runGit", "GitRepository"]),
      any("git/repository.ts"),
      types("core/facts/types.ts"),
    ],
  },
];
