import { any } from "./policy-helpers.js";

export const contractHandleZones = [
  {
    source: "library/contract-forwarding-reconciliation-result.ts",
    allow: [any("git/identity.ts", ["mintSnapshotId"])],
  },
  {
    source: "library/contract*.ts",
    allow: [
      any("akuma/requests.ts"),
      any("body/amend.ts"),
      any("body/arc.ts"),
      any("body/decode.ts"),
      any("contract*.ts"),
      any("core/facts/**"),
      any("dispatch/index.ts"),
      any("git/identity.ts"),
      any("git/observe.ts"),
      any("git/read-observation.ts"),
      any("library/audit.ts"),
      any("library/configuration.ts"),
      any("library/continuation.ts"),
      any("library/contract*.ts"),
      any("library/delivery.ts"),
      any("library/input.ts"),
      any("library/mutation.ts"),
      any("library/reconcile.ts"),
      any("library/refusal.ts"),
      any("library/region.ts"),
      any("library/repo.ts"),
      any("markdown/diff.ts"),
      any("protocol/abandon.ts"),
      any("protocol/amend.ts"),
      any("protocol/arc.ts"),
      any("protocol/audit.ts"),
      any("protocol/deliver.ts"),
      any("protocol/operations.ts"),
      any("protocol/read/status.ts"),
      any("protocol/reconcile.ts"),
      any("protocol/review.ts"),
      any("settlement/holder.ts"),
      any("settlement/settle.ts"),
      any("task/identity.ts"),
    ],
    deny: [
      any("library/bind.ts"),
      any("protocol/placement.ts"),
      any("protocol/run.ts"),
      any("protocol/audit.ts", ["auditOperation"]),
    ],
  },
];
