import type { ArchitecturePolicy } from "./engine.js";

export const capabilityPolicy = {
  sensitiveImports: [
    { module: "node:module", owners: [] },
    { module: "module", owners: [] },
    { module: "zod", owners: [{ source: "akuma/**" }, { source: "library/**" }, { source: "task/**" }] },
    {
      module: "node:child_process",
      owners: [{ source: "git/**" }, { source: "runtime/proc/**" }, { source: "scripts/**" }],
    },
    { module: "child_process", owners: [] },
    {
      module: "node:fs",
      owners: [
        { source: "cli/draft.ts" },
        { source: "coordination/**" },
        { source: "scripts/**" },
        { source: "task/store.ts" },
      ],
    },
    { module: "fs", owners: [] },
    {
      module: "node:fs/promises",
      owners: [
        { source: "akuma/**" },
        { source: "alias/**" },
        { source: "cli/**" },
        { source: "contract-worktree.ts" },
        { source: "coordination/**" },
        { source: "git/**" },
        { source: "library/**" },
        { source: "runtime/proc/**" },
        { source: "settings.ts" },
        { source: "settlement/**" },
        { source: "task/**" },
        { source: "workspace-place.ts" },
        { source: "world.ts" },
      ],
    },
    { module: "fs/promises", owners: [] },
    {
      module: "node:crypto",
      owners: [
        { source: "akuma/**" },
        { source: "body/**" },
        { source: "cli/**" },
        { source: "coordination/**" },
        { source: "dispatch/**" },
        { source: "git/**" },
        { source: "library/**" },
        { source: "protocol/**" },
        { source: "settlement/**" },
        { source: "task/**" },
        { source: "workspace-place.ts" },
      ],
    },
    { module: "node:sqlite", owners: [{ source: "akuma/heart/**" }, { source: "coordination/**" }] },
    { module: "crypto", owners: [] },
  ],
  forbiddenSourcePatterns: [
    {
      source: "**",
      pattern: /\bas\s+(?:unknown\s+as\s+)?WorldRoot\b/u,
      detail: "only World may mint WorldRoot; raw runtime coordinates must use World.prove before product effects",
    },
    {
      source: "akuma/providers/index.ts",
      pattern: /^import .*\.\/.*\/index\.js";$/mu,
      detail: "provider resolution imports only the selected adapter at the execution edge",
    },
    {
      source: "akuma/**",
      pattern: /(?:awaitLateDisposal|lateDisposal|WeakMap\s*<\s*AbortSignal)/u,
      detail: "provider attempts, not AbortSignal-keyed state, own cleanup proof",
    },
    {
      source: "git/read-observation.ts",
      pattern: /(?:contracts\/|settlement\/task-holders|dispatch\/|decodeJournal|decodeHolder)/u,
      detail: "Git read observation is product-blind; product paths and codecs remain with their owners",
    },
    {
      source: "git/read-observation.ts",
      pattern: /(?:\bclass\b|#[A-Za-z_$])/u,
      detail: "Git decode ownership uses one structural callback capability, not nominal or private-field machinery",
    },
    {
      source: "git/read-observation.ts",
      pattern: /withGitDecodeChannel\s*\(/u,
      detail: "read observations consume their caller's channel and never create a compatibility channel",
    },
    {
      source: "git/repository.ts",
      pattern: /symref-(?:update|create|delete)/u,
      detail: "admission assertions never change symbolic refs or caller-owned checkout state",
    },
    {
      source: "kanshi/read.ts",
      pattern: /(?:\.snapshot\b|\.readBlobs\s*\(|\.resolveRef\s*\()/u,
      detail: "Kanshi composes owner projections and must not inspect or consume Git observation mechanics",
    },
    {
      source: "akuma/heart/index.ts",
      pattern: /\b(?:SELECT|INSERT|UPDATE|DELETE)\b/iu,
      detail: "Heart SQL belongs to schema mechanics or named fact statements, never the transaction judge",
    },
    {
      source: "akuma/heart/index.ts",
      pattern: /\.prepare\s*\(/u,
      detail: "Heart index owns adjudication and must execute SQL through schema.ts or rows.ts",
    },
  ],
  forbiddenModules: ["better-sqlite3", "sqlite3"],
  capabilityRules: [
    { capability: "dynamic-import-nonliteral", owners: [] },
    { capability: "eval", owners: [] },
    { capability: "function-constructor", owners: [] },
    { capability: "math-random", owners: [] },
    { capability: "module-mutable-state", owners: [] },
    { capability: "date-now", owners: ["cli/**", "protocol/**"] },
    { capability: "new-date-current", owners: ["akuma/**", "dispatch/**", "kanshi/**", "protocol/**", "task/**"] },
    { capability: "process-argv", owners: ["akuma-body.ts", "akuma/body.ts", "cli/**", "git/hooks.ts", "scripts/**"] },
    {
      capability: "process-cwd",
      owners: ["akuma/**", "cli/**", "git/**", "kanshi/**", "library/**", "scripts/**", "task/**"],
    },
    {
      capability: "process-environment",
      owners: ["akuma-body.ts", "akuma/**", "cli/**", "git/**", "protocol/**", "runtime/proc/**"],
    },
    { capability: "process-output", owners: ["akuma-body.ts", "cli/**", "scripts/**"] },
    { capability: "process-pid", owners: ["runtime/proc/**"] },
    { capability: "require", owners: [] },
    {
      capability: "type-error-construction",
      owners: [
        "akuma/**",
        "akuma-body.ts",
        "alias/**",
        "body/**",
        "cli/**",
        "contract-worktree.ts",
        "identity/**",
        "kanshi/**",
        "library/**",
        "settings.ts",
        "task/**",
        "workspace-place.ts",
        "world.ts",
      ],
    },
  ],
  forbiddenFileNames: [
    "approval-preparation.ts",
    "claim.ts",
    "forfeit.ts",
    "open.ts",
    "petition-preparation.ts",
    "petition.ts",
    "pipeline.ts",
    "renew.ts",
    "seal.ts",
  ],
  forbiddenDeclarations: [
    /(?:Open|Seal|Renew|Petition|Claim|Forfeit)(?:Data|Entry|Input|Refusal|Decision|Offer|State|Result)$/,
  ],
  verbDirectory: "core/verbs/",
  providerSdkRoots: [
    { module: "@agentclientprotocol/sdk", root: "akuma/providers/acp" },
    { module: "@anthropic-ai/claude-agent-sdk", root: "akuma/providers/claude" },
    { module: "@earendil-works/pi-coding-agent", root: "akuma/providers/pi" },
    { module: "@opencode-ai/sdk", root: "akuma/providers/opencode-sdk" },
  ],
  runtimeGraphRoots: ["cli/parse.ts"],
} as const satisfies Omit<ArchitecturePolicy, "zones">;
