import type { ArchitecturePolicy } from "./engine.js";

const any = (target: string, symbols?: readonly string[]) => (symbols ? { target, symbols } : { target });
const types = (...args: Parameters<typeof any>) => ({ ...any(...args), mode: "type-only" as const });
const factErrors = any("core/facts/errors.ts");
const factTypes = any("core/facts/types.ts");
const gitRepository = types("git/process.ts", ["GitRepository"]);
const ownersFor = (symbols: readonly string[], ...sources: readonly string[]) =>
  sources.map((source) => ({ source, symbols }));
const forbiddenFor = (source: string, guards: readonly Readonly<{ pattern: RegExp; detail: string }>[]) =>
  guards.map(({ pattern, detail }) => ({ source, pattern, detail }));
export const KEIYAKU_ARCHITECTURE_POLICY = {
  zones: [
    {
      source: "akuma-body.ts",
      allow: [
        any("akuma/body.ts", ["LEASH_HELD_EXIT", "runAkumaBody", "BodyLaunch"]),
        any("akuma/identity.ts", ["worldRootForAkumaPaths"]),
        any("task/mutation.ts", ["executeTaskMutation"]),
        types("akuma/request-serve.ts", ["UpstreamExecutionPort"]),
        any("library/fleet.ts", ["executeKillAkuma", "executeTellAkuma", "executeWaitAkuma"]),
        any("library/configuration.ts", ["requireBranchesToBeUpToDateFrom", "worktreeHooksFrom"]),
        any("library/contract.ts", ["executeForwardedDeliver", "executeForwardedReview"]),
        any("library/repo.ts", ["Repo"]),
        any("settings.ts", ["settings"]),
        types("world.ts"),
      ],
    },
    { source: "akuma/abort.ts", allow: [] },
    { source: "duration.ts", allow: [] },
    { source: "settings.ts", allow: [] },
    { source: "world.ts", allow: [] },
    { source: "coordination/**", allow: [] },
    { source: "identity/coordinates.ts", allow: [] },
    { source: "identity/normalize.ts", allow: [] },
    { source: "identity/selector.ts", allow: [any("identity/normalize.ts")] },
    { source: "akuma/identity.ts", allow: [any("identity/coordinates.ts"), any("identity/normalize.ts")] },
    { source: "akuma/provider-recipe.ts", allow: [] },
    { source: "akuma/allowed.ts", allow: [any("task/mutation.ts", ["TASK_MUTATION_ACTIONS"])] },
    {
      source: "akuma/heart/facts.ts",
      allow: [
        types("akuma/identity.ts"),
        types("akuma/coordinate.ts"),
        types("akuma/provider-recipe.ts"),
        types("akuma/allowed.ts"),
        types("task/mutation.ts"),
      ],
    },
    { source: "akuma/heart/schema.ts", allow: [] },
    { source: "akuma/coordinate.ts", allow: [] },
    {
      source: "akuma/heart/rows.ts",
      allow: [types("akuma/heart/facts.ts"), types("akuma/provider-recipe.ts"), any("akuma/coordinate.ts")],
    },
    {
      source: "akuma/heart/request-rows.ts",
      allow: [
        types("akuma/heart/facts.ts"),
        types("akuma/identity.ts"),
        any("task/mutation.ts", ["isTaskMutationAction"]),
      ],
    },
    { source: "akuma/heart/tells.ts", allow: [types("akuma/heart/facts.ts")] },
    {
      source: "akuma/heart/timeline.ts",
      allow: [
        types("akuma/heart/facts.ts"),
        any("akuma/heart/rows.ts", [
          "decodeActivityRow",
          "decodeCallRow",
          "decodeTurnRow",
          "ActivityFact",
          "ActivityRow",
          "CallRow",
          "TurnRow",
        ]),
        any("akuma/heart/tells.ts", ["decodeTellAtSequence", "pendingTellProtectionSql", "pendingTellSequencesSql"]),
      ],
    },
    {
      source: "akuma/heart/soul.ts",
      allow: [
        any("akuma/allowed.ts"),
        any("akuma/identity.ts", ["parseAkuId", "AkuId"]),
        any("akuma/provider-recipe.ts"),
        types("akuma/heart/facts.ts"),
      ],
    },
    {
      source: "akuma/heart/storage.ts",
      allow: [
        types("akuma/identity.ts"),
        types("akuma/heart/facts.ts"),
        any("akuma/heart/schema.ts"),
        any("akuma/heart/rows.ts"),
        any("akuma/heart/soul.ts"),
        any("akuma/heart/tells.ts", ["insertTellFact"]),
        any("akuma/heart/timeline.ts", ["pruneActivityFacts"]),
      ],
    },
    {
      source: "akuma/heart/request-authority.ts",
      allow: [
        any("akuma/allowed.ts"),
        types("akuma/identity.ts"),
        types("akuma/heart/facts.ts"),
        any("akuma/heart/request-rows.ts"),
        any("akuma/heart/soul.ts", ["soulFact"]),
        any("akuma/heart/storage.ts"),
      ],
    },
    {
      source: "akuma/heart/index.ts",
      allow: [
        types("akuma/identity.ts"),
        types("akuma/coordinate.ts"),
        any("akuma/heart/facts.ts"),
        any("akuma/heart/request-authority.ts"),
        any("akuma/heart/rows.ts"),
        any("akuma/heart/soul.ts", ["soulFact"]),
        any("akuma/heart/tells.ts"),
        any("akuma/heart/timeline.ts"),
        any("akuma/heart/storage.ts"),
      ],
    },
    {
      source: "akuma/provider.ts",
      allow: [types("akuma/heart/index.ts"), any("akuma/coordinate.ts"), types("akuma/provider-recipe.ts")],
    },
    { source: "akuma/projection.ts", allow: [types("akuma/heart/index.ts"), any("akuma/provider.ts")] },
    {
      source: "akuma/providers/index.ts",
      allow: [
        types("akuma/provider.ts"),
        any("akuma/provider-recipe.ts"),
        any("akuma/providers/acp/config.ts"),
        any("akuma/providers/acp/index.ts"),
        any("akuma/providers/claude/index.ts"),
        any("akuma/providers/codex-app-server/index.ts"),
        any("akuma/providers/grok-build/index.ts"),
        any("akuma/providers/opencode-sdk/index.ts"),
        any("akuma/providers/pi/index.ts"),
      ],
    },
    {
      source: "akuma/providers/claude/index.ts",
      allow: [
        any("akuma/abort.ts"),
        any("akuma/provider.ts"),
        any("akuma/provider-recipe.ts", ["ProviderOptions", "providerLaunchEnv"]),
        any("akuma/providers/claude/events.ts"),
        any("akuma/providers/claude/input.ts"),
      ],
    },
    {
      source: "akuma/providers/pi/index.ts",
      allow: [
        any("akuma/abort.ts"),
        any("akuma/providers/pi/events.ts"),
        any("akuma/provider.ts"),
        types("akuma/provider-recipe.ts"),
        types("akuma/coordinate.ts"),
      ],
    },
    {
      source: "akuma/providers/pi/events.ts",
      allow: [any("akuma/provider.ts"), any("akuma/providers/unified-patch.ts")],
    },
    {
      source: "akuma/providers/codex-app-server/index.ts",
      allow: [
        any("akuma/providers/codex-app-server/events.ts"),
        any("akuma/provider.ts"),
        any("akuma/provider-recipe.ts", ["ProviderExecution", "ProviderOptions", "providerLaunchEnv"]),
        any("runtime/proc/line-rpc.ts"),
      ],
    },
    {
      source: "akuma/providers/acp/core.ts",
      allow: [
        any("akuma/abort.ts"),
        any("akuma/providers/acp/events.ts"),
        any("akuma/provider.ts"),
        any("akuma/provider-recipe.ts", ["providerLaunchEnv"]),
        any("runtime/proc/stdio.ts"),
      ],
    },
    { source: "akuma/providers/acp/config.ts", allow: [types("akuma/provider-recipe.ts", ["SystemPromptMode"])] },
    {
      source: "akuma/providers/acp/index.ts",
      allow: [
        types("akuma/provider.ts"),
        types("akuma/provider-recipe.ts"),
        any("akuma/providers/acp/config.ts"),
        any("akuma/providers/acp/core.ts"),
      ],
    },
    {
      source: "akuma/providers/grok-build/index.ts",
      allow: [types("akuma/provider.ts"), types("akuma/provider-recipe.ts"), any("akuma/providers/acp/core.ts")],
    },
    {
      source: "akuma/providers/codex-app-server/events.ts",
      allow: [any("akuma/provider.ts"), any("akuma/providers/unified-patch.ts"), types("runtime/proc/line-rpc.ts")],
    },
    {
      source: "akuma/providers/opencode-sdk/index.ts",
      allow: [
        any("akuma/abort.ts"),
        any("akuma/providers/opencode-sdk/events.ts"),
        any("akuma/providers/opencode-sdk/session.ts"),
        any("akuma/provider.ts"),
        types("akuma/heart/index.ts"),
        types("akuma/provider-recipe.ts"),
      ],
    },
    {
      source: "akuma/providers/opencode-sdk/session.ts",
      allow: [
        any("akuma/abort.ts"),
        types("akuma/heart/index.ts"),
        any("akuma/provider-recipe.ts", ["ProviderExecution", "providerLaunchEnv"]),
        any("runtime/proc/run.ts"),
      ],
    },
    {
      source: "akuma/providers/**",
      allow: [
        types("akuma/heart/index.ts"),
        any("akuma/provider.ts"),
        types("akuma/provider-recipe.ts"),
        any("runtime/proc/line-rpc.ts"),
      ],
    },
    {
      source: "akuma/archetype.ts",
      allow: [
        any("akuma/allowed.ts"),
        any("akuma/identity.ts"),
        types("akuma/provider.ts", ["ProviderAdapter"]),
        any("akuma/provider-recipe.ts"),
        any("akuma/providers/index.ts", ["resolveProviderExecution"]),
        types("settings.ts"),
      ],
    },
    {
      source: "akuma/publication.ts",
      allow: [any("akuma/abort.ts"), any("akuma/heart/index.ts"), any("akuma/identity.ts"), any("runtime/proc/run.ts")],
    },
    {
      source: "akuma/request-wire.ts",
      allow: [
        any("akuma/allowed.ts", ["decodeAllowedActions"]),
        any("akuma/identity.ts", ["archetypeName", "parseAkuId", "AkuId"]),
        any("akuma/provider-recipe.ts", ["decodeProviderOptions", "decodeReadonlyRestraint", "ReadonlyRestraint"]),
        any("akuma/providers/index.ts", ["decodeProviderExecution"]),
        any("task/mutation.ts", [
          "TaskMutationAction",
          "TaskMutationRequest",
          "decodeTaskMutationRequest",
          "isTaskMutationAction",
        ]),
      ],
    },
    {
      source: "akuma/requests.ts",
      allow: [
        any("akuma/abort.ts", ["abortableDelay"]),
        any("akuma/provider.ts", ["AKUMA_REQUESTS_ENV"]),
        any("akuma/request-wire.ts", [
          "absolute",
          "atomicJson",
          "decodeReceipt",
          "receiptPath",
          "requestPath",
          "requestPayload",
          "CallRequestClaim",
          "DeliverRequestClaim",
          "ForwardedDeliveryReference",
          "ForwardedReviewReference",
          "KillRequestClaim",
          "RequestClaim",
          "RequestReceipt",
          "ReviewRequestClaim",
          "TellRequestClaim",
          "UpstreamRequestOutcome",
          "WaitRequestClaim",
        ]),
        any("task/mutation.ts", ["TaskMutationRequest", "isTaskMutationAction"]),
      ],
    },
    {
      source: "akuma/request-serve.ts",
      allow: [
        any("akuma/abort.ts", ["abortableDelay"]),
        any("akuma/heart/index.ts", [
          "HeldAkumaLeash",
          "admitRequest",
          "readNonterminalRequests",
          "readRequest",
          "readSoul",
          "refuseRequest",
          "reserveRequest",
          "serveRequest",
          "serveUpstreamRequest",
          "voidRequest",
          "KillEvidence",
          "RequestFact",
          "Soul",
          "UpstreamRequestService",
        ]),
        any("akuma/identity.ts", ["pathsForAkuId", "worldRootForAkumaPaths", "AkuId", "AkumaPaths"]),
        any("akuma/publication.ts", ["BIRTH_TIMEOUT_MS", "publishAkuma"]),
        any("akuma/request-wire.ts", [
          "atomicJson",
          "canonicalAkuId",
          "decodeClaim",
          "decodeRecipe",
          "receiptPath",
          "RequestReceipt",
          "StructuralRequestClaim",
          "TaskRequestClaim",
          "UpstreamRequestFailure",
          "UpstreamRequestOutcome",
        ]),
        any("task/mutation.ts", ["TaskMutationRequest", "isTaskMutationAction"]),
      ],
    },
    {
      source: "akuma/body.ts",
      allow: [
        any("akuma/abort.ts"),
        any("akuma/heart/index.ts"),
        types("akuma/identity.ts"),
        any("akuma/body-turn.ts", ["BodySupervisor", "CONTROL_RESPONSE_MS", "driveTurn", "DrivenTurn", "turnRecipe"]),
        types("akuma/provider.ts", ["ProviderAdapter"]),
        any("akuma/providers/index.ts"),
        any("akuma/request-serve.ts", [
          "clearBodyRequestTransport",
          "settleBodyRequests",
          "UpstreamExecutionPort",
          "RequestChildLaunch",
        ]),
        any("runtime/proc/run.ts"),
      ],
    },
    {
      source: "akuma/body-turn.ts",
      allow: [
        any("akuma/abort.ts", ["abortableDelay"]),
        any("akuma/heart/index.ts", [
          "appendActivity",
          "beginTurn",
          "breakBody",
          "heartExists",
          "readHeart",
          "recordSession",
          "recordTellDeliveries",
          "recordTellReceipt",
          "HeartSnapshot",
          "HeldAkumaLeash",
          "ResumeCoordinate",
          "Soul",
          "TellFact",
        ]),
        types("akuma/identity.ts"),
        any("akuma/provider.ts", ["AgentEvent", "encodeAgentEvent", "ProviderAdapter", "Session", "TurnResult"]),
        any("akuma/request-serve.ts", ["BodyRequestPump", "RequestChildLaunch", "UpstreamExecutionPort"]),
      ],
    },
    {
      source: "akuma/akuma.ts",
      allow: [
        any("akuma/allowed.ts"),
        any("akuma/body.ts"),
        any("akuma/projection.ts"),
        any("akuma/heart/index.ts"),
        any("akuma/identity.ts"),
        any("akuma/archetype.ts"),
        any("akuma/publication.ts"),
        types("akuma/provider-recipe.ts", ["ReadonlyRestraint"]),
        any("akuma/providers/index.ts"),
        any("akuma/requests.ts"),
        any("settings.ts"),
        types("world.ts"),
      ],
    },
    {
      source: "akuma/nuke.ts",
      allow: [
        any("akuma/body.ts", ["CONTROL_RESPONSE_MS"]),
        any("akuma/heart/index.ts", ["HeldAkumaLeash", "readHeart", "readKill", "requestStop"]),
        any("akuma/identity.ts", ["akuIdFromDirectoryName", "akumaPaths", "akumaRunRoot", "AkuId", "AkumaPaths"]),
        any("alias/index.ts", ["nukeAliases"]),
        types("world.ts", ["WorldRoot"]),
      ],
    },
    {
      source: "akuma/index.ts",
      allow: [
        any("akuma/allowed.ts"),
        any("akuma/akuma.ts"),
        any("akuma/archetype.ts"),
        any("akuma/requests.ts"),
        any("akuma/heart/index.ts", ["readSoul"]),
        types("akuma/heart/index.ts"),
        any("akuma/identity.ts", ["pathsForAkuId", "AkuId"]),
        types("akuma/provider.ts"),
        types("akuma/provider-recipe.ts"),
        types("world.ts"),
      ],
    },
    {
      source: "dispatch/index.ts",
      allow: [
        any("akuma/identity.ts", ["parseAkuId", "AkuId"]),
        any("coordination/sqlite-transaction-lock.ts"),
        factErrors,
        factTypes,
        any("git/read-observation.ts"),
        gitRepository,
        any("git/repository.ts"),
      ],
    },
    {
      source: "alias/index.ts",
      allow: [
        any("akuma/identity.ts", ["parseAkuId", "AkuId"]),
        any("coordination/durable-file.ts"),
        any("coordination/sqlite-transaction-lock.ts"),
        factErrors,
        any("identity/selector.ts"),
        types("world.ts"),
      ],
    },
    { source: "core/facts/types.ts", allow: [any("identity/coordinates.ts")] },
    { source: "core/facts/errors.ts", allow: [] },
    {
      source: "core/facts/codec.ts",
      allow: [factErrors, factTypes, any("core/subject.ts", ["parseDependencyKeySet"])],
    },
    {
      source: "core/facts/fold.ts",
      allow: [
        any("core/facts/eligibility.ts", ["samePrerequisites"]),
        factErrors,
        any("core/facts/gate.ts"),
        factTypes,
      ],
    },
    { source: "core/facts/gate.ts", allow: [any("core/subject.ts"), types("core/facts/types.ts")] },
    { source: "core/subject.ts", allow: [factErrors, factTypes] },
    {
      source: "core/facts/eligibility.ts",
      allow: [any("core/facts/observation.ts"), types("core/facts/offer.ts"), types("core/facts/types.ts")],
    },
    { source: "core/facts/offer.ts", allow: [types("core/facts/types.ts")] },
    { source: "core/facts/observation.ts", allow: [types("core/facts/types.ts")] },
    {
      source: "core/decide.ts",
      allow: [types("core/facts/observation.ts"), types("core/facts/offer.ts"), types("core/facts/types.ts")],
    },
    {
      source: "core/verbs/**",
      allow: [
        types("core/decide.ts"),
        types("core/facts/offer.ts"),
        any("core/facts/eligibility.ts", [
          "placeEligibleBounds",
          "prerequisiteStatus",
          "prerequisitesReach",
          "samePrerequisites",
        ]),
        any("core/facts/gate.ts"),
        any("core/facts/observation.ts", [
          "activeContract",
          "contractState",
          "documentIsCurrent",
          "prerequisiteStatus",
        ]),
        types("core/facts/types.ts"),
      ],
    },
    { source: "git/identity.ts", allow: [factTypes] },
    { source: "git/tree.ts", allow: [any("git/identity.ts")] },
    { source: "git/process.ts", allow: [any("runtime/proc/run.ts", ["consumeProcessStdout"])] },
    {
      source: "git/repository.ts",
      allow: [
        any("git/identity.ts"),
        any("git/tree.ts"),
        factErrors,
        any("git/process.ts", ["GitPlumbingError", "runGit", "runGitWithEnvironment", "GitRepository"]),
      ],
    },
    {
      source: "git/read-observation.ts",
      allow: [
        factErrors,
        any("git/identity.ts"),
        any("git/process.ts", ["GitPlumbingError", "GitRepository"]),
        any("git/repository.ts"),
        any("git/tree.ts", ["parseTreeObject", "TreeEntry", "validPath"]),
      ],
    },
    {
      source: "git/admission.ts",
      allow: [
        any("git/identity.ts"),
        types("git/observe.ts"),
        gitRepository,
        any("git/repository.ts"),
        any("git/tree.ts", ["validPath"]),
        any("core/facts/codec.ts"),
        types("core/facts/offer.ts"),
        types("core/facts/types.ts"),
      ],
    },
    {
      source: "git/observe.ts",
      allow: [
        any("git/identity.ts"),
        any("git/read-observation.ts", [
          "GitBlobResult",
          "GitDecodeChannel",
          "GitReadObservation",
          "GitTreeSelection",
          "readGitTreeSelection",
          "withGitReadObservation",
          "withGitTargetedReadObservation",
        ]),
        any("git/repository.ts"),
        any("git/process.ts", ["GitPlumbingError", "runGit", "GitRepository"]),
        factErrors,
        any("core/facts/codec.ts"),
        any("core/facts/fold.ts"),
        types("core/facts/observation.ts"),
        types("core/facts/types.ts"),
      ],
    },
    {
      source: "git/tender.ts",
      allow: [
        any("git/identity.ts"),
        any("git/repository.ts"),
        any("git/process.ts", ["GitPlumbingError", "runGit", "runGitWithEnvironment", "GitRepository"]),
        any("git/workspace.ts", [
          "captureWorkspaceTree",
          "unmergedWorkspacePaths",
          "workspaceMergeHead",
          "worktreePath",
        ]),
        types("core/decide.ts"),
        types("core/facts/types.ts"),
      ],
    },
    {
      source: "git/integration.ts",
      allow: [
        any("git/identity.ts"),
        any("git/repository.ts"),
        any("git/process.ts", ["GitPlumbingError", "runGit", "runGitWithEnvironment", "GitRepository"]),
        any("git/workspace.ts", ["workspaceMergeStatePresent"]),
        types("git/tender.ts"),
        factErrors,
        types("core/decide.ts"),
        types("core/facts/types.ts"),
      ],
    },
    {
      source: "git/workspace.ts",
      allow: [
        types("core/facts/types.ts"),
        any("git/identity.ts"),
        any("git/process.ts", ["GitPlumbingError", "runGit", "runGitWithEnvironment", "GitRepository"]),
        any("git/repository.ts"),
        types("world.ts"),
      ],
    },
    {
      source: "git/nuke.ts",
      allow: [
        any("contract-worktree.ts", ["nukeContractWorktreeLock"]),
        types("core/facts/types.ts", ["ContractId"]),
        any("git/hooks.ts", ["nukeWorktreeHookResidue"]),
        any("git/process.ts", ["runGit", "GitRepository"]),
        any("git/repository.ts", ["NoGitWorldError", "registeredWorktrees", "repositoryAt", "worktreeGitDirectory"]),
        any("git/workspace.ts", ["worktreePath"]),
        any("workspace-place.ts", ["nukeEmptyPlaceAuthority", "readPlaceRegister", "releaseManagedWorktrees"]),
        types("world.ts", ["WorldRoot"]),
      ],
    },
    {
      source: "git/target-placement.ts",
      allow: [
        any("coordination/sqlite-transaction-lock.ts"),
        types("core/facts/offer.ts"),
        types("core/facts/types.ts"),
        any("git/identity.ts"),
        any("git/observe.ts", ["currentBranch"]),
        any("git/process.ts", ["consumeGitStdout", "GitPlumbingError", "runGit", "GitRepository"]),
        any("git/repository.ts"),
        any("git/workspace.ts", ["captureWorkspaceTree"]),
      ],
    },
    {
      source: "git/reconcile.ts",
      allow: [
        any("coordination/sqlite-transaction-lock.ts"),
        factErrors,
        types("core/facts/types.ts"),
        any("git/hooks.ts"),
        any("git/identity.ts"),
        any("git/observe.ts"),
        types("git/read-observation.ts", ["GitDecodeChannel"]),
        any("git/read-observation.ts", ["withGitDecodeChannel"]),
        any("git/process.ts", ["GitPlumbingError", "runGit", "GitRepository"]),
        any("git/repository.ts"),
        any("git/target-placement.ts"),
        any("git/terminal-seal.ts"),
        any("git/workspace.ts", ["followManagedWorktree", "worktreePath"]),
        any("git/scratch.ts", ["collectableScratchWorktrees"]),
      ],
    },
    {
      source: "workspace-place.ts",
      allow: [
        any("coordination/durable-file.ts", ["replaceFileDurably"]),
        any("coordination/sqlite-transaction-lock.ts"),
        any("core/facts/errors.ts", ["AuthorityCorruptionError"]),
        any("core/facts/types.ts", ["contractId", "ContractId"]),
        gitRepository,
        any("git/workspace.ts", ["worktreePath"]),
      ],
    },
    {
      source: "contract-worktree.ts",
      allow: [
        any("coordination/durable-file.ts"),
        any("coordination/sqlite-transaction-lock.ts"),
        any("core/facts/errors.ts", ["AuthorityCorruptionError"]),
        factTypes,
        any("git/process.ts", ["GitPlumbingError", "runGit", "GitRepository"]),
        any("git/repository.ts"),
        any("git/workspace.ts", ["worktreePath"]),
        any("workspace-place.ts", ["appointmentFor", "placeRegisterPath", "readPlaceRegister", "PlaceRegister"]),
      ],
    },
    {
      source: "git/terminal-seal.ts",
      allow: [
        types("core/facts/types.ts"),
        any("git/identity.ts"),
        any("git/process.ts", ["runGit", "GitRepository"]),
        any("git/repository.ts"),
        any("git/workspace.ts", ["captureWorkspaceTree"]),
      ],
    },
    {
      source: "git/hooks.ts",
      allow: [
        any("coordination/durable-file.ts"),
        any("coordination/sqlite-transaction-lock.ts"),
        any("runtime/proc/run.ts"),
      ],
    },
    {
      source: "git/scratch.ts",
      allow: [
        any("coordination/sqlite-transaction-lock.ts"),
        any("git/identity.ts"),
        any("git/process.ts", ["runGit", "GitRepository"]),
        any("git/repository.ts"),
        types("core/facts/types.ts"),
      ],
    },
    {
      source: "protocol/attempt.ts",
      allow: [
        any("git/admission.ts"),
        any("git/observe.ts"),
        types("git/read-observation.ts", ["GitDecodeChannel"]),
        any("git/repository.ts", ["GIT_REF", "GitRefAssertion", "readRef"]),
        gitRepository,
        types("core/decide.ts"),
        any("core/facts/codec.ts"),
        factErrors,
        any("core/facts/fold.ts", ["foldJournal"]),
        types("core/facts/offer.ts"),
        factTypes,
      ],
    },
    {
      source: "protocol/run.ts",
      allow: [
        any("git/observe.ts"),
        types("git/read-observation.ts"),
        types("git/repository.ts", ["GitRefAssertion"]),
        gitRepository,
        types("core/decide.ts"),
        types("core/facts/offer.ts"),
        types("core/facts/types.ts"),
        any("protocol/attempt.ts"),
      ],
    },
    {
      source: "protocol/outcome.ts",
      allow: [
        types("core/facts/types.ts"),
        types("git/reconcile.ts"),
        types("git/scratch.ts"),
        types("protocol/attempt.ts"),
        types("protocol/intent.ts"),
        types("protocol/run.ts"),
      ],
    },
    {
      source: "protocol/bind.ts",
      allow: [
        any("git/observe.ts"),
        any("git/identity.ts", ["gitObjectIdForSnapshot"]),
        types("git/read-observation.ts", ["GitDecodeChannel"]),
        any("git/repository.ts"),
        gitRepository,
        factTypes,
        any("core/verbs/bind.ts"),
        any("protocol/intent.ts"),
        any("protocol/outcome.ts"),
        types("protocol/run.ts"),
        types("verification/declaration.ts"),
      ],
    },
    {
      source: "protocol/intent.ts",
      allow: [
        any("git/observe.ts"),
        types("git/read-observation.ts", ["GitDecodeChannel", "GitTreeSelection"]),
        any("git/scratch.ts", ["materializeScratchCandidate", "WorktreeLeak"]),
        types("git/hooks.ts", ["HookFailure"]),
        any("settings.ts", ["projectSettings"]),
        types("git/repository.ts", ["GitRefAssertion"]),
        gitRepository,
        types("core/decide.ts"),
        types("core/facts/types.ts"),
        any("core/subject.ts", ["dependencyKeySet"]),
        any("core/verbs/attestation.ts"),
        any("protocol/attempt.ts", ["mintAttempts"]),
        any("protocol/run.ts"),
        any("verification/execution.ts"),
        any("verification/declaration.ts", ["VERIFIED", "VerificationDefinition"]),
        any("core/facts/gate.ts", ["latestCurrentAttestations"]),
      ],
    },
    {
      source: "protocol/placement.ts",
      allow: [
        any("coordination/sqlite-transaction-lock.ts", ["SqliteTransactionLockError"]),
        any("core/facts/errors.ts", ["AuthorityCorruptionError"]),
        any("core/facts/observation.ts", ["contractState"]),
        types("core/facts/types.ts"),
        any("core/verbs/placement.ts"),
        any("git/observe.ts", ["observeGitForAdmissionAt"]),
        types("git/read-observation.ts", ["GitDecodeChannel"]),
        any("git/reconcile.ts", ["ReconcileResult", "reconcileEffectFailure"]),
        any("git/process.ts", ["GitPlumbingError", "GitRepository"]),
        any("git/target-placement.ts"),
        any("protocol/attempt.ts", ["AcceptedAdmission", "admitDecidedOffer", "mintAttempts"]),
        any("protocol/run.ts"),
      ],
    },
    {
      source: "protocol/operations.ts",
      allow: [
        any("git/integration.ts", ["readDeliveryDiff"]),
        types("git/integration.ts", ["IntegrationPreparationRefusal"]),
        types("git/tender.ts", ["DirtyWorkspaceRefusal"]),
        any("git/observe.ts", ["currentBranch", "observeContractAt"]),
        any("git/read-observation.ts", ["GitDecodeChannel", "withGitReadObservation"]),
        any("git/repository.ts"),
        gitRepository,
        types("git/scratch.ts", ["WorktreeLeak"]),
        types("git/target-placement.ts", ["TargetPlacementRefusal"]),
        types("core/facts/types.ts"),
        types("core/verbs/abandon.ts"),
        types("core/verbs/amend.ts"),
        types("core/verbs/arc.ts"),
        types("core/verbs/bind.ts"),
        types("core/verbs/deliver.ts"),
        types("core/verbs/placement.ts"),
        types("core/verbs/attestation.ts"),
        types("protocol/attempt.ts"),
        types("protocol/bind.ts"),
        types("protocol/intent.ts"),
        types("protocol/outcome.ts"),
        types("protocol/placement.ts"),
        any("protocol/read/documents.ts"),
        any("protocol/read/status.ts"),
        types("protocol/run.ts"),
        types("verification/declaration.ts"),
      ],
    },
    {
      source: "protocol/amend.ts",
      allow: [
        any("git/observe.ts", ["extendContractsForAdmissionAt", "observeContractsForAdmissionAt"]),
        types("git/observe.ts", ["GitDecisionObservation"]),
        types("git/read-observation.ts", ["GitDecodeChannel"]),
        any("core/facts/observation.ts", ["contractState"]),
        types("core/facts/types.ts", ["AmendData", "ContractId", "ContractTerms"]),
        any("core/verbs/amend.ts", ["AmendInput", "AmendRefusal", "decideAmend"]),
        types("verification/declaration.ts", ["VerificationDeclarationPreparation", "VerificationDeclarationRefusal"]),
        any("protocol/attempt.ts", ["admitDecidedOffer", "mintAttempts"]),
        any("protocol/outcome.ts", ["admitted"]),
        types("protocol/operations.ts", ["MutationOperationInput", "IntentOutcome"]),
        any("protocol/operations.ts", ["timestamp"]),
      ],
    },
    {
      source: "protocol/completion.ts",
      allow: [
        types("core/facts/types.ts", ["ActorId", "ContractId", "SnapshotId"]),
        types("git/scratch.ts", ["WorktreeLeak"]),
        gitRepository,
        types("git/read-observation.ts", ["GitDecodeChannel"]),
        types("verification/declaration.ts", ["VerificationDeclarationPreparation"]),
        any("protocol/intent.ts"),
        any("protocol/placement.ts", ["admitPlacement"]),
        any("protocol/reintegrate.ts"),
        types("protocol/outcome.ts", ["AcceptedProtocolStep"]),
        types("protocol/operations.ts", ["PlacementStop", "VerificationStop"]),
        any("protocol/operations.ts", ["mergeAdmissions", "placementStop", "timestamp", "unpackVerificationOutcome"]),
      ],
    },
    {
      source: "protocol/reintegrate.ts",
      allow: [
        any("core/facts/observation.ts", ["contractState"]),
        types("core/facts/types.ts", ["ActorId", "ContractId", "ReintegratedData"]),
        any("core/verbs/reintegrate.ts"),
        any("git/integration.ts"),
        any("git/observe.ts", ["observeContractsForAdmissionAt"]),
        gitRepository,
        types("git/read-observation.ts", ["GitDecodeChannel"]),
        types("git/repository.ts", ["GitRefAssertion"]),
        any("protocol/attempt.ts"),
        any("protocol/operations.ts", ["timestamp"]),
        types("protocol/run.ts", ["ProtocolTerminal"]),
        any("protocol/placement.ts"),
      ],
    },
    {
      source: "protocol/deliver.ts",
      allow: [
        any("git/integration.ts", [
          "materializeIntegrationSnapshot",
          "materializeJudgedConflict",
          "planIntegration",
          "workspaceMergeStatePresent",
          "worktreeChangeId",
        ]),
        any("git/workspace.ts", ["worktreePath"]),
        any("git/tender.ts", [
          "captureTender",
          "dirtyTenderRefusal",
          "materializeTenderSnapshot",
          "prepareDeliveryCommitMetadata",
        ]),
        any("git/observe.ts", ["currentBranch", "observeContractsForAdmissionAt"]),
        gitRepository,
        types("core/decide.ts", ["AttemptContext"]),
        any("core/facts/observation.ts", ["contractState"]),
        types("core/facts/types.ts", [
          "ActorId",
          "ContractId",
          "ContractState",
          "DeliverData",
          "JournalEntry",
          "SnapshotId",
        ]),
        any("core/verbs/deliver.ts", ["DeliverInput", "DeliverRefusal", "decideDeliver"]),
        types("verification/declaration.ts", ["VerificationDeclarationRefusal"]),
        types("protocol/intent.ts", ["CurrentVerifiedAttestation"]),
        any("protocol/completion.ts"),
        any("protocol/attempt.ts", ["admitDecidedOffer", "mintAttempts"]),
        any("protocol/outcome.ts", ["admitted"]),
        any("workspace-place.ts", ["ManagedWorktreeAppointment", "appointmentFor", "readPlaceRegister"]),
        types("protocol/operations.ts", [
          "AttemptDecision",
          "DeliverConflictRefusal",
          "DeliveryPreparationRefusal",
          "DocumentDerivation",
          "IntentOutcome",
          "IntentRefusal",
          "MutationOperationInput",
        ]),
        any("protocol/operations.ts", ["timestamp"]),
      ],
    },
    {
      source: "protocol/review.ts",
      allow: [
        any("git/integration.ts", ["worktreeChangeId"]),
        any("git/tender.ts", [
          "TenderCapture",
          "WorkspaceDirtyDelta",
          "captureTender",
          "dirtyTenderDelta",
          "dirtyTenderRefusal",
        ]),
        types("git/tender.ts", ["DirtyWorkspaceRefusal"]),
        any("git/observe.ts", ["observeContractsForAdmissionAt"]),
        any("core/subject.ts", ["dependencyKeySet"]),
        types("core/decide.ts", ["AttemptContext"]),
        any("core/facts/observation.ts", ["contractState"]),
        any("core/facts/types.ts", ["gate"]),
        types("core/facts/types.ts", ["AttestationData", "ContractId", "ContractState", "DeliverData"]),
        any("core/verbs/attestation.ts", ["AttestationInput", "AttestationRefusal", "decideAttestation"]),
        any("protocol/attempt.ts", ["admitDecidedOffer", "mintAttempts"]),
        any("protocol/outcome.ts", ["admitted"]),
        any("protocol/completion.ts"),
        any("workspace-place.ts", ["appointmentFor", "readPlaceRegister"]),
        types("protocol/operations.ts", [
          "AttemptDecision",
          "DocumentDerivation",
          "IntentOutcome",
          "MutationOperationInput",
          "RepositoryScope",
        ]),
        any("protocol/operations.ts", ["timestamp"]),
      ],
    },
    {
      source: "protocol/audit.ts",
      allow: [
        any("git/integration.ts", ["DeliveryDiffScope", "readDeliveryDiff", "readDeliveryScope"]),
        any("git/observe.ts", ["observeContractsForAdmissionAt"]),
        any("git/target-placement.ts", ["AuditTargetAnswer", "adjudicateAuditTarget"]),
        any("core/facts/observation.ts", ["activeContract", "documentIsCurrent"]),
        types("core/facts/types.ts", ["ChangeId", "ContractState", "DeliverData", "SnapshotId"]),
        any("workspace-place.ts", ["ManagedWorktreeAppointment", "readManagedWorktreeAppointment"]),
        any("protocol/intent.ts", ["verifyDelivery"]),
        any("protocol/outcome.ts", ["accepted", "admitted"]),
        types("protocol/operations.ts", [
          "DeliveryPreparationRefusal",
          "DocumentDerivation",
          "IntentOutcome",
          "MutationOperationInput",
          "RepositoryScope",
          "VerificationStop",
        ]),
        any("protocol/operations.ts", ["timestamp", "unpackVerificationOutcome"]),
        any("protocol/deliver.ts", ["prepareDelivery"]),
      ],
    },
    {
      source: "protocol/abandon.ts",
      allow: [
        any("core/verbs/abandon.ts", ["AbandonRefusal", "decideAbandon"]),
        types("git/read-observation.ts", ["GitTreeSelection"]),
        any("protocol/intent.ts", ["admitIntent"]),
        any("protocol/outcome.ts", ["complete"]),
        types("protocol/run.ts", ["CompanionDecorator"]),
        types("protocol/operations.ts", ["IntentOutcome", "MutationOperationInput"]),
        any("protocol/operations.ts", ["timestamp"]),
      ],
    },
    {
      source: "protocol/arc.ts",
      allow: [
        types("core/facts/types.ts", ["ArcData"]),
        any("core/verbs/arc.ts", ["ArcRefusal", "decideArc"]),
        any("protocol/intent.ts", ["admitIntent"]),
        any("protocol/outcome.ts", ["complete"]),
        types("protocol/operations.ts", ["IntentOutcome", "MutationOperationInput"]),
        any("protocol/operations.ts", ["timestamp"]),
      ],
    },
    {
      source: "protocol/reconcile.ts",
      allow: [
        any("git/reconcile.ts", ["ReconcileResult", "reconcile", "reconcileBatch", "reconcileObservationFailure"]),
        any("git/observe.ts", ["observeContractWorld"]),
        any("git/read-observation.ts", ["withGitReadObservation"]),
        types("git/read-observation.ts", ["GitDecodeChannel"]),
        any("core/facts/errors.ts", ["AuthorityCorruptionError"]),
        types("core/facts/types.ts", ["ContractId", "ContractState"]),
        types("git/hooks.ts", ["WorktreeHooks"]),
        types("protocol/operations.ts", ["MutationOperationInput", "RepositoryScope"]),
      ],
    },
    {
      source: "protocol/read/observation.ts",
      allow: [
        any("git/hooks.ts", ["observeWorktreeHookMarker"]),
        types("git/process.ts", ["GitRepository"]),
        any("git/repository.ts", ["registeredWorktrees", "worktreeGitDirectory"]),
        any("git/target-placement.ts", ["observeTargetCheckoutShape"]),
        types("protocol/read/status.ts", ["ContractRow"]),
      ],
    },
    {
      source: "protocol/read/status.ts",
      allow: [
        any("git/observe.ts"),
        any("git/read-observation.ts", ["GitDecodeChannel", "GitReadObservation", "withGitReadObservation"]),
        gitRepository,
        any("git/workspace.ts", ["worktreePath", "observeTargetLag", "observeWorkspace"]),
        any("workspace-place.ts", ["PlaceRegister", "appointmentFor", "readPlaceRegister"]),
        types("git/workspace.ts", ["ContractTargetLag", "ContractWorkspaceObservation"]),
        any("body/decode.ts", ["decodeContractDocument"]),
        any("core/facts/gate.ts", ["GateCurrent", "gateReports"]),
        any("core/facts/observation.ts", ["prerequisiteStatus"]),
        any("core/facts/types.ts", ["ContractId", "ContractState", "SnapshotId"]),
        types("core/facts/types.ts"),
        types("protocol/read/status.ts", ["ContractRow"]),
      ],
    },
    {
      source: "protocol/read/documents.ts",
      allow: [
        any("git/observe.ts", ["observeActiveContractWorld"]),
        types("git/read-observation.ts", ["GitReadObservation"]),
        types("core/facts/types.ts", ["ContractId"]),
      ],
    },
    { source: "runtime/proc/line-rpc.ts", allow: [any("runtime/proc/stdio.ts")] },
    { source: "runtime/proc/stdio.ts", allow: [any("runtime/proc/run.ts"), any("runtime/proc/launch.ts")] },
    { source: "runtime/proc/run.ts", allow: [any("runtime/proc/launch.ts")] },
    { source: "runtime/proc/launch.ts", allow: [] },
    {
      source: "verification/declaration.ts",
      allow: [
        types("core/decide.ts"),
        any("core/facts/types.ts", ["ContractId", "DocumentSegmentKey", "Gate", "gate"]),
      ],
    },
    {
      source: "verification/execution.ts",
      allow: [
        types("core/facts/types.ts"),
        any("git/hooks.ts"),
        any("library/configuration.ts", ["worktreeHooksFrom"]),
        types("git/scratch.ts"),
        gitRepository,
        types("settings.ts"),
        any("runtime/proc/run.ts"),
        types("verification/declaration.ts"),
      ],
    },
    {
      source: "library/bind.ts",
      allow: [
        any("body/decode.ts", ["decodeContractDocument"]),
        any("core/facts/errors.ts", ["AuthorityCorruptionError"]),
        any("contract-worktree.ts"),
        factTypes,
        types("git/read-observation.ts", ["GitDecodeChannel"]),
        any("identity/normalize.ts", ["fitIdentityStem", "normalizeIdentityStem"]),
        any("protocol/operations.ts", ["IntentOutcome", "RepositoryScope", "stateOperation"]),
        any("protocol/bind.ts", ["BindTargetSelection", "bindOperation"]),
        any("settlement/holder.ts", ["claimTaskHolder", "claimTaskHolderWithFence"]),
        types("task/identity.ts", ["TaskId"]),
        types("verification/declaration.ts", ["VerificationDeclarationPreparation"]),
        any("library/refusal.ts", ["KeiyakuRefusal", "KeiyakuRefused"]),
        any("library/input.ts", ["contractTerms", "documentDerivation"]),
      ],
    },
    {
      source: "library/contract.ts",
      allow: [
        any("akuma/requests.ts", [
          "UpstreamRequestOutcome",
          "injectedBodyRequests",
          "requestBodyDeliver",
          "requestBodyReview",
        ]),
        any("body/amend.ts"),
        any("markdown/diff.ts"),
        any("body/arc.ts"),
        any("body/decode.ts"),
        any("contract-worktree.ts"),
        factErrors,
        factTypes,
        types("protocol/read/status.ts", [
          "AfterEndpointObservation",
          "ContractAfterEdge",
          "ContractBoard",
          "ContractDependent",
          "ContractDisposition",
          "ContractGateCurrent",
          "ContractGateReport",
          "ContractObservation",
          "ContractPhase",
          "ContractRow",
          "ContractWorkspaceObservation",
        ]),
        any("protocol/operations.ts", [
          "contractObservationOperation",
          "contractsOperation",
          "deliveryDiffOperation",
          "deliveryOperation",
          "stateOperation",
          "DeliveryPreparationRefusal",
          "PlacementStop",
          "RepositoryScope",
          "VerificationStop",
        ]),
        any("protocol/abandon.ts", ["abandonOperation"]),
        any("protocol/amend.ts", ["amendOperation"]),
        any("protocol/arc.ts", ["arcOperation"]),
        types("protocol/audit.ts", ["AuditReport"]),
        any("protocol/deliver.ts", ["deliverOperation", "IntegrationConflictMaterialized", "VerificationReuse"]),
        types("protocol/reconcile.ts", ["ReconcileReport"]),
        any("protocol/review.ts", ["reviewOperation", "ReviewValue"]),
        any("dispatch/index.ts", ["Dispatch", "readDispatchesAt"]),
        any("git/identity.ts", ["mintSnapshotId"]),
        any("git/observe.ts", ["observeContractsForAdmissionInObservationAt"]),
        any("git/read-observation.ts", ["GitDecodeChannel", "withGitDecodeChannel", "withGitReadObservation"]),
        any("library/audit.ts", ["auditContract", "AuditInput"]),
        any("library/delivery.ts"),
        any("library/bind.ts", ["admitForkBindWithAppointment", "prepareMarkdownBind"]),
        any("library/refusal.ts"),
        any("library/mutation.ts"),
        any("library/reconcile.ts", ["completeReconcile"]),
        any("library/input.ts"),
        any("library/region.ts"),
        any("library/configuration.ts"),
        any("library/continuation.ts", ["ContinuationReport", "continueAcceptedCompletion"]),
        any("library/repo.ts"),
        any("settlement/holder.ts"),
        any("settlement/settle.ts"),
        types("task/identity.ts", ["TaskId"]),
      ],
    },
    {
      source: "library/audit.ts",
      allow: [
        any("body/decode.ts", ["decodeContractDocument"]),
        types("core/facts/types.ts"),
        any("git/read-observation.ts", ["withGitDecodeChannel"]),
        any("protocol/audit.ts", ["auditOperation", "AuditReport"]),
        types("protocol/operations.ts", ["RepositoryScope"]),
        any("library/configuration.ts", ["worktreeHooksOption", "WorktreeHooks"]),
        any("library/input.ts", [
          "actorOption",
          "documentDerivation",
          "optionalBoolean",
          "optionalSignal",
          "requireInput",
        ]),
        any("library/mutation.ts", ["completeMutation", "MutationResult"]),
        any("library/refusal.ts", ["requireAccepted"]),
      ],
    },
    {
      source: "library/delivery.ts",
      allow: [
        types("core/facts/types.ts"),
        types("protocol/deliver.ts", ["DeliverValue"]),
        types("library/continuation.ts", ["ContinuationReport"]),
      ],
    },
    {
      source: "library/continuation.ts",
      allow: [
        types("core/facts/types.ts", ["ActorId", "ContractId", "ContractState", "JournalEntry"]),
        any("git/observe.ts", ["observeActiveContractWorld"]),
        any("git/read-observation.ts", ["GitDecodeChannel", "withGitReadObservation"]),
        any("protocol/deliver.ts", ["continueDeliveryOperation"]),
        any("protocol/operations.ts", ["DocumentDerivation", "PlacementStop", "RepositoryScope"]),
        types("library/mutation.ts", ["AcceptedIntent"]),
      ],
    },
    {
      source: "library/mutation.ts",
      allow: [
        types("core/facts/types.ts"),
        any("git/read-observation.ts", ["GitDecodeChannel", "withGitDecodeChannel"]),
        types("protocol/operations.ts", ["IntentOutcome", "RepositoryScope"]),
        types("protocol/reconcile.ts", ["ReconcileReport"]),
        types("protocol/outcome.ts", ["AcceptedObligations"]),
        types("settlement/holder.ts", ["TaskHolderAdmission"]),
        any("settlement/settle.ts", ["deferredTaskHolderSettlement", "SettlementReport"]),
        types("library/configuration.ts", ["WorktreeHooks"]),
        any("library/reconcile.ts", ["completeReconcile", "ReconcileCompletion"]),
      ],
    },
    {
      source: "library/reconcile.ts",
      allow: [
        any("contract-worktree.ts", ["projectContractWorktree", "ContractFileEffect", "ContractFileLag"]),
        any("workspace-place.ts", [
          "appointManagedWorktrees",
          "placeRegisterPath",
          "PlaceRegister",
          "releaseManagedWorktrees",
        ]),
        types("core/facts/types.ts"),
        any("core/facts/errors.ts", ["AuthorityCorruptionError"]),
        types("git/read-observation.ts", ["GitDecodeChannel"]),
        any("protocol/reconcile.ts", [
          "reconcileAllOperation",
          "reconcileOperation",
          "worldContractStates",
          "ReconcileReport",
        ]),
        any("git/reconcile.ts", ["reconcileObservationFailure"]),
        any("protocol/operations.ts", ["stateOperation", "RepositoryScope"]),
        any("settlement/settle.ts", ["settle", "settleAll", "SettlementReport"]),
        types("library/configuration.ts", ["WorktreeHooks"]),
      ],
    },
    {
      source: "library/refusal.ts",
      allow: [
        types("core/facts/types.ts", ["ContractId"]),
        types("protocol/operations.ts", ["IntentOutcome", "IntentRefusal", "IntentRetry"]),
        types("library/mutation.ts", ["AcceptedIntent"]),
      ],
    },
    {
      source: "library/repo.ts",
      allow: [
        any("protocol/operations.ts"),
        any("git/repository.ts", ["NoGitWorldError"]),
        any("git/read-observation.ts", ["withGitDecodeChannel"]),
        any("library/configuration.ts"),
        any("library/input.ts"),
        any("library/reconcile.ts", ["completeRepoReconcile", "RepoContractReconcileReport", "RepoReconcileReport"]),
      ],
    },
    {
      source: "library/keiyaku.ts",
      allow: [
        types("akuma/allowed.ts"),
        types("akuma/identity.ts"),
        types("alias/index.ts"),
        factErrors,
        types("core/facts/types.ts"),
        types("dispatch/index.ts"),
        types("identity/selector.ts"),
        any("library/contract.ts"),
        any("library/repo.ts"),
        any("library/configuration.ts"),
        any("library/akuma-creation.ts"),
        any("library/fleet.ts"),
        any("library/catalog.ts"),
        any("library/address.ts"),
        any("library/nuke.ts"),
        types("library/refusal.ts", ["NukeConfirmationRefusal", "NukeConfirmationRequiredRefusal"]),
        types("library/region.ts"),
        types("settlement/settle.ts"),
        types("world.ts"),
      ],
    },
    {
      source: "library/nuke.ts",
      allow: [
        any("akuma/nuke.ts", ["nukeAkuma", "stopAkuma"]),
        any("git/nuke.ts", ["nukeGit"]),
        any("task/operations.ts", ["nukeTask"]),
        any("library/input.ts", ["requireInput", "requireMarkdown"]),
        any("library/refusal.ts", ["KeiyakuRefused"]),
        types("world.ts", ["WorldRoot"]),
      ],
    },
    {
      source: "library/akuma-creation.ts",
      allow: [
        any("alias/index.ts"),
        types("akuma/allowed.ts"),
        any("akuma/akuma.ts"),
        any("akuma/identity.ts", ["parseAkuId", "AkuId"]),
        factErrors,
        types("core/facts/types.ts", ["ContractId"]),
        any("dispatch/index.ts"),
        any("identity/selector.ts"),
        any("library/contract.ts", ["Keiyaku", "KeiyakuRefused", "seatForKeiyaku"]),
        any("library/input.ts", ["requireInput"]),
        any("library/address.ts", ["addressAkuma"]),
        any("library/repo.ts", ["Repo", "scopeForRepo"]),
        any("workspace-place.ts", ["readManagedWorktreeAppointment"]),
        types("settings.ts"),
        types("world.ts"),
      ],
    },
    {
      source: "library/address.ts",
      allow: [
        any("alias/index.ts", ["AliasBinding", "readAliases"]),
        any("akuma/akuma.ts", ["Akuma", "AkumaList"]),
        any("akuma/index.ts", ["probeBornAkuma"]),
        any("akuma/identity.ts", ["parseAkuId", "AkuId"]),
        any("core/facts/types.ts", ["contractId"]),
        any("dispatch/index.ts", ["readDispatches"]),
        any("identity/selector.ts"),
        types("kanshi/index.ts"),
        any("library/input.ts", ["requireInput"]),
        any("library/repo.ts", ["Repo", "scopeForRepo"]),
        types("world.ts"),
      ],
    },
    {
      source: "library/fleet.ts",
      allow: [
        any("akuma/index.ts"),
        any("akuma/akuma.ts", ["readBudgetedStatus", "tellAkumaWithId"]),
        any("akuma/requests.ts", [
          "injectedBodyRequests",
          "requestBodyKill",
          "requestBodyTell",
          "requestBodyWait",
          "UpstreamRequestOutcome",
        ]),
        types("core/facts/types.ts", ["ContractId"]),
        any("dispatch/index.ts", ["readDispatch"]),
        any("library/address.ts"),
        any("library/input.ts", ["requireInput"]),
        any("library/repo.ts", ["Repo", "scopeForRepo"]),
        types("task/index.ts"),
        any("task/operations.ts", ["observeTaskBoard"]),
        types("world.ts"),
      ],
    },
    {
      source: "library/catalog.ts",
      allow: [
        any("akuma/akuma.ts", ["Akuma", "AkumaList"]),
        any("akuma/archetype.ts", ["ArchetypeCatalogRow", "listArchetypeDefinitions"]),
        types("task/index.ts", ["TaskRow"]),
        any("task/operations.ts", ["observeTaskCatalogRows"]),
        any("library/contract.ts", ["ContractBoard", "listKeiyaku"]),
        any("library/input.ts", ["requireInput"]),
        any("library/repo.ts", ["Repo"]),
        types("world.ts"),
      ],
    },
    {
      source: "library/input.ts",
      allow: [
        any("body/decode.ts", ["verificationDefinition"]),
        types("body/types.ts"),
        any("core/facts/types.ts", ["ActorId", "ContractId", "ContractTerms", "Gate", "actorId", "gate", "gateWord"]),
        any("task/identity.ts", ["parseTaskId", "TaskId"]),
        types("protocol/operations.ts", ["DocumentDerivation"]),
        any("verification/declaration.ts", ["prepareVerificationDeclaration"]),
      ],
    },
    {
      source: "library/configuration.ts",
      allow: [
        any("core/facts/types.ts", ["gateWord"]),
        any("settings.ts", ["Settings", "SettingsError"]),
        types("git/hooks.ts"),
      ],
    },
    {
      source: "library/region.ts",
      allow: [
        any("body/decode.ts"),
        any("body/region.ts"),
        types("core/facts/types.ts"),
        types("protocol/read/documents.ts", ["ContractDocumentProjection"]),
        any("git/read-observation.ts", ["GitDecodeChannel", "withGitDecodeChannel"]),
        any("protocol/operations.ts", ["RepositoryScope", "documentsOperationAt"]),
      ],
    },
    {
      source: "index.ts",
      allow: [any("library/keiyaku.ts"), any("settings.ts"), any("world.ts")],
    },
    { source: "markdown/**", allow: [any("markdown/lex.ts"), any("markdown/types.ts"), any("markdown/diff.ts")] },
    { source: "task/identity.ts", allow: [any("identity/coordinates.ts"), any("identity/normalize.ts")] },
    { source: "task/context.ts", allow: [any("coordination/durable-file.ts"), any("identity/normalize.ts")] },
    { source: "task/document.ts", allow: [any("task/identity.ts")] },
    { source: "task/board.ts", allow: [types("task/document.ts"), any("task/identity.ts")] },
    {
      source: "task/store.ts",
      allow: [
        types("world.ts"),
        any("coordination/sqlite-transaction-lock.ts"),
        any("task/board.ts"),
        any("task/document.ts"),
        any("task/identity.ts"),
      ],
    },
    { source: "task/query.ts", allow: [any("task/board.ts"), types("task/document.ts"), any("task/identity.ts")] },
    {
      source: "task/operations.ts",
      allow: [
        types("world.ts"),
        any("markdown/diff.ts"),
        any("task/context.ts"),
        any("task/board.ts"),
        any("task/document.ts"),
        any("task/identity.ts"),
        any("task/query.ts"),
        any("task/store.ts"),
      ],
    },
    {
      source: "task/compose.ts",
      allow: [
        types("world.ts"),
        any("markdown/diff.ts"),
        any("task/context.ts"),
        any("task/board.ts"),
        any("task/document.ts"),
        any("task/identity.ts"),
        any("task/operations.ts"),
        any("task/store.ts"),
      ],
    },
    {
      source: "task/input.ts",
      allow: [any("task/document.ts"), any("task/identity.ts"), types("task/operations.ts"), any("task/query.ts")],
    },
    {
      source: "task/mutation.ts",
      allow: [
        types("world.ts"),
        types("task/compose.ts"),
        any("task/input.ts"),
        any("task/index.ts"),
        types("task/identity.ts"),
        types("task/operations.ts"),
      ],
    },
    {
      source: "task/index.ts",
      allow: [
        types("world.ts"),
        any("task/board.ts"),
        any("task/compose.ts"),
        any("task/document.ts"),
        any("task/identity.ts"),
        any("task/input.ts"),
        any("task/operations.ts"),
        any("task/query.ts"),
        any("task/store.ts"),
      ],
    },
    {
      source: "settlement/fence.ts",
      allow: [
        any("coordination/sqlite-transaction-lock.ts"),
        any("git/repository.ts"),
        gitRepository,
        types("task/identity.ts"),
      ],
    },
    {
      source: "settlement/holder.ts",
      allow: [
        factErrors,
        types("core/facts/offer.ts"),
        factTypes,
        types("git/observe.ts", ["GitDecisionObservation"]),
        any("git/read-observation.ts"),
        any("git/repository.ts"),
        gitRepository,
        any("settlement/fence.ts"),
        any("task/identity.ts"),
      ],
    },
    {
      source: "settlement/settle.ts",
      allow: [
        any("world.ts"),
        any("git/observe.ts"),
        any("git/read-observation.ts"),
        types("git/reconcile.ts"),
        gitRepository,
        factTypes,
        any("settlement/fence.ts"),
        any("settlement/holder.ts"),
        any("task/context.ts"),
        any("task/operations.ts"),
        types("task/identity.ts"),
        types("task/store.ts"),
      ],
    },
    {
      source: "kanshi/read.ts",
      allow: [
        types("world.ts"),
        any("akuma/index.ts"),
        any("alias/index.ts", ["AliasBinding", "readAliases"]),
        any("dispatch/index.ts", ["Dispatch", "readDispatchesAt"]),
        any("git/read-observation.ts", ["GitReadObservation", "withGitDecodeChannel", "withGitReadObservation"]),
        any("kanshi/**"),
        any("library/region.ts", ["readRegionDeclarations", "validateRegionPatterns"]),
        any("core/facts/types.ts", ["contractId"]),
        types("library/contract.ts"),
        any("library/repo.ts", ["Repo", "scopeForRepo"]),
        any("protocol/read/status.ts", ["readContractBoard"]),
        any("protocol/read/observation.ts", ["observeCurrentPhysicalIssue"]),
        any("protocol/read/documents.ts", ["readDocuments"]),
        any("settlement/holder.ts", ["TaskHolderProjection", "readTaskHolderProjectionAt"]),
        any("settlement/settle.ts", ["contractNamespace"]),
        types("task/index.ts"),
        any("task/operations.ts", ["observeTaskBoard"]),
      ],
    },
    {
      source: "kanshi/report.ts",
      allow: [
        types("world.ts"),
        types("akuma/index.ts"),
        types("identity/selector.ts"),
        types("library/contract.ts"),
        types("library/region.ts", ["RegionOverlap"]),
        types("protocol/read/observation.ts", ["CurrentPhysicalIssue"]),
        types("task/index.ts"),
      ],
    },
    { source: "kanshi/fleet.ts", allow: [types("kanshi/report.ts", ["AkumaKanshiRow"])] },
    { source: "kanshi/select.ts", allow: [types("kanshi/report.ts"), any("library/region.ts", ["regionOverlaps"])] },
    { source: "kanshi/**", allow: [any("index.ts"), any("kanshi/**"), any("task/index.ts")] },
    {
      source: "body/amend.ts",
      allow: [
        any("body/region.ts"),
        any("body/render.ts"),
        any("body/shape.ts"),
        types("body/types.ts"),
        any("body/verification.ts"),
        any("markdown/parse.ts"),
        any("markdown/query.ts"),
        types("markdown/types.ts"),
        types("verification/declaration.ts"),
      ],
    },
    {
      source: "body/**",
      allow: [
        any("body/envelope.ts"),
        any("body/keys.ts"),
        any("body/region.ts"),
        any("body/shape.ts"),
        types("body/types.ts"),
        any("body/verification.ts"),
        any("markdown/parse.ts"),
        any("markdown/query.ts"),
        types("markdown/types.ts"),
        factTypes,
        any("duration.ts"),
        types("verification/declaration.ts"),
      ],
    },
    {
      source: "cli/commands/akuma.ts",
      allow: [
        any("akuma/allowed.ts"),
        any("akuma/identity.ts", ["archetypeName", "parseAkuId", "AkuId"]),
        any("cli/usage.ts"),
        any("duration.ts"),
        any("identity/selector.ts"),
      ],
    },
    {
      source: "cli/commands/akuma-invoke.ts",
      allow: [
        any("akuma/index.ts"),
        any("index.ts"),
        types("cli/commands/akuma.ts"),
        types("settings.ts"),
        types("world.ts"),
      ],
    },
    {
      source: "cli/commands/install.ts",
      allow: [any("cli/usage.ts"), any("runtime/proc/run.ts")],
    },
    {
      source: "cli/commands/task-query.ts",
      allow: [
        types("task/document.ts", ["TaskPriority", "TaskState"]),
        types("task/identity.ts", ["TaskId"]),
        any("task/query.ts", [
          "MAX_TASK_LIMIT",
          "TASK_RELATION_PREDICATE_FIELDS",
          "normalizeTaskQuery",
          "TaskQueryExpression",
          "TaskQueryPredicate",
        ]),
      ],
    },
    {
      source: "cli/commands/task.ts",
      allow: [any("cli/commands/task-query.ts"), any("cli/usage.ts")],
    },
    {
      source: "cli/commands/task-invoke.ts",
      allow: [
        types("cli/commands/task.ts"),
        any("cli/usage.ts", ["CliUsageError"]),
        any("task/index.ts"),
        any("task/operations.ts", ["observeTaskDetails"]),
        any("task/context.ts", ["resolveTaskNamespaceContext", "writeTaskNamespaceContext"]),
        any("task/mutation.ts"),
        types("world.ts"),
        any("akuma/requests.ts", ["injectedBodyRequests", "requestBodyTask"]),
      ],
    },
    {
      source: "cli/draft.ts",
      allow: [any("coordination/durable-file.ts"), types("cli/result.ts"), types("world.ts")],
    },
    { source: "cli/render/akuma-tool-command.ts", allow: [] },
    { source: "cli/render/akuma-tool.ts", allow: [types("akuma/index.ts"), any("cli/render/akuma-tool-command.ts")] },
    {
      source: "cli/render/akuma.ts",
      allow: [
        any("akuma/index.ts", ["defaultWaitComplete"]),
        types("akuma/index.ts"),
        types("index.ts"),
        types("cli/commands/akuma-invoke.ts"),
        types("cli/parse.ts"),
        any("cli/render/akuma-tool.ts"),
        any("cli/render/terminal.ts", [
          "TextRenderContext",
          "displayColumns",
          "renderBoundedTextBlock",
          "safeText",
          "truncateMiddleDisplayText",
        ]),
      ],
    },
    {
      source: "cli/render/catalog.ts",
      allow: [
        types("index.ts"),
        any("cli/render/contract-observation.ts"),
        any("cli/render/terminal.ts", ["safeText"]),
      ],
    },
    { source: "cli/render/contract-observation.ts", allow: [types("index.ts")] },
    {
      source: "cli/main.ts",
      allow: [any("cli/parse.ts"), any("cli/runtime.ts")],
    },
    {
      source: "cli/parse.ts",
      allow: [
        any("cli/commands/akuma.ts"),
        any("cli/commands/contract.ts"),
        any("cli/commands/install.ts"),
        any("cli/commands/task.ts"),
        any("cli/usage.ts"),
      ],
    },
    {
      source: "cli/coordinates.ts",
      allow: [any("cli/parse.ts"), any("library/repo.ts", ["NoGitWorldError", "Repo"]), any("world.ts")],
    },
    {
      source: "cli/runtime.ts",
      allow: [
        types("cli/commands/akuma.ts"),
        types("cli/commands/akuma-invoke.ts"),
        types("cli/commands/install.ts"),
        types("cli/commands/task-invoke.ts"),
        types("cli/parse.ts"),
        types("cli/result.ts"),
        types("settings.ts"),
        any("cli/commands/akuma.ts", ["isParsedAkumaCommand"]),
        any("cli/commands/install.ts"),
        any("cli/draft.ts"),
        any("cli/invoke.ts"),
        any("cli/parse.ts", ["CliUsageError"]),
        any("cli/render/**"),
        any("library/address.ts"),
      ],
    },
    {
      source: "cli/commands/amend.ts",
      allow: [types("index.ts"), types("cli/commands/contract.ts", ["ParsedAmend"]), any("cli/selectors.ts")],
    },
    {
      source: "cli/commands/bind.ts",
      allow: [
        any("index.ts"),
        any("library/contract.ts", ["bindFromCli"]),
        types("cli/commands/contract.ts", ["ParsedBind"]),
        any("cli/selectors.ts"),
      ],
    },
    { source: "cli/commands/contract.ts", allow: [types("library/catalog.ts", ["CatalogQuery"])] },
    {
      source: "cli/invoke.ts",
      allow: [
        types("index.ts"),
        types("kanshi/index.ts"),
        types("library/repo.ts"),
        types("world.ts"),
        types("cli/commands/akuma.ts"),
        types("cli/commands/akuma-invoke.ts"),
        types("cli/commands/install.ts"),
        types("cli/commands/task-invoke.ts"),
        types("cli/result.ts"),
        any("cli/accepted.ts"),
        any("cli/actor.ts"),
        any("cli/commands/**"),
        any("cli/coordinates.ts"),
        any("cli/draft.ts"),
        any("cli/parse.ts"),
        any("cli/selectors.ts"),
        any("cli/usage.ts"),
        any("akuma/requests.ts"),
        any("kanshi/index.ts"),
        any("library/address.ts"),
        any("library/configuration.ts"),
        any("library/keiyaku.ts"),
        any("settings.ts"),
      ],
    },
    { source: "scripts/architecture/**", allow: [types("scripts/architecture/engine.ts")] },
    {
      source: "scripts/check-architecture.ts",
      allow: [any("scripts/architecture/engine.ts"), any("scripts/architecture/policy.ts")],
    },
    { source: "scripts/model-impact/**", allow: [types("scripts/model-impact/engine.ts")] },
    {
      source: "cli/accepted.ts",
      allow: [any("index.ts"), types("library/region.ts"), any("cli/result.ts")],
    },
    { source: "cli/actor.ts", allow: [types("index.ts")] },
    {
      source: "cli/commands/nuke.ts",
      allow: [any("index.ts"), types("world.ts"), any("cli/parse.ts"), types("cli/result.ts")],
    },
    { source: "cli/index.ts", allow: [any("cli/main.ts")] },
    {
      source: "cli/render/audit.ts",
      allow: [
        types("index.ts"),
        types("cli/result.ts"),
        any("cli/render/receipt.ts"),
        any("cli/render/refusal.ts"),
        any("cli/render/terminal.ts"),
      ],
    },
    { source: "cli/render/board.ts", allow: [types("cli/result.ts")] },
    {
      source: "cli/render/contract.ts",
      allow: [
        types("index.ts"),
        types("cli/result.ts"),
        any("cli/render/audit.ts"),
        any("cli/render/receipt.ts"),
        any("cli/render/terminal.ts"),
      ],
    },
    {
      source: "cli/render/kanshi.ts",
      allow: [
        types("index.ts"),
        types("kanshi/index.ts"),
        any("kanshi/fleet.ts"),
        any("cli/render/contract-observation.ts"),
        any("cli/render/terminal.ts"),
      ],
    },
    { source: "cli/render/nuke.ts", allow: [types("index.ts")] },
    {
      source: "cli/render/receipt.ts",
      allow: [types("index.ts"), types("cli/result.ts"), any("cli/render/terminal.ts")],
    },
    {
      source: "cli/render/refusal.ts",
      allow: [types("index.ts"), types("cli/result.ts"), any("cli/render/terminal.ts")],
    },
    { source: "cli/render/region.ts", allow: [types("kanshi/index.ts")] },
    { source: "cli/render/settings.ts", allow: [types("settings.ts")] },
    {
      source: "cli/render/task.ts",
      allow: [
        types("task/index.ts"),
        types("cli/commands/task-invoke.ts"),
        types("cli/commands/task.ts"),
        any("cli/render/receipt.ts"),
        any("cli/render/terminal.ts"),
      ],
    },
    { source: "cli/render/terminal.ts", allow: [] },
    {
      source: "cli/render/text.ts",
      allow: [
        types("cli/result.ts"),
        any("cli/render/board.ts"),
        any("cli/render/contract.ts"),
        any("cli/render/kanshi.ts"),
        any("cli/render/refusal.ts"),
        types("cli/render/terminal.ts"),
        any("cli/render/catalog.ts"),
        any("cli/render/nuke.ts"),
        any("cli/render/region.ts"),
      ],
    },
    {
      source: "cli/result.ts",
      allow: [types("index.ts"), types("kanshi/index.ts"), types("library/region.ts")],
    },
    {
      source: "cli/selectors.ts",
      allow: [any("identity/coordinates.ts"), any("index.ts"), types("kanshi/index.ts"), any("cli/parse.ts")],
    },
    { source: "cli/usage.ts", allow: [] },
    {
      source: "scripts/model-change-impact.ts",
      allow: [any("scripts/model-impact/engine.ts"), any("scripts/model-impact/policy.ts")],
    },
  ],
  sensitiveImports: [
    { module: "node:module", owners: [] },
    { module: "module", owners: [] },
    {
      module: "node:child_process",
      owners: [
        { source: "git/process.ts", symbols: ["spawn"] },
        { source: "git/read-observation.ts", symbols: ["ChildProcessWithoutNullStreams", "spawn"] },
        { source: "runtime/proc/**", symbols: ["ChildProcess", "ChildProcessWithoutNullStreams", "execFile", "spawn"] },
        { source: "scripts/model-change-impact.ts", symbols: ["execFileSync"] },
      ],
    },
    { module: "child_process", owners: [] },
    {
      module: "node:fs",
      owners: [
        ...ownersFor(
          ["readFileSync", "readdirSync"],
          "scripts/check-architecture.ts",
          "scripts/model-change-impact.ts",
        ),
        ...ownersFor(
          ["closeSync", "fsyncSync", "openSync", "renameSync", "writeFileSync"],
          "task/store.ts",
          "coordination/durable-file.ts",
        ),
        {
          source: "cli/draft.ts",
          symbols: ["lstatSync", "mkdirSync", "readFileSync", "readdirSync", "unlinkSync", "utimesSync"],
        },
        { source: "akuma/heart/storage.ts", symbols: ["watch"] },
      ],
    },
    { module: "fs", owners: [] },
    {
      module: "node:fs/promises",
      owners: [
        { source: "world.ts", symbols: ["mkdir", "realpath", "stat"] },
        { source: "settings.ts", symbols: ["readFile"] },
        ...ownersFor(["realpath"], "cli/coordinates.ts", "git/scratch.ts"),
        { source: "akuma/archetype.ts", symbols: ["readFile", "readdir"] },
        { source: "akuma/akuma.ts", symbols: ["readdir", "realpath", "stat"] },
        { source: "akuma/nuke.ts", symbols: ["lstat", "readdir", "rm"] },
        ...ownersFor(["lstat", "watch"], "akuma/heart/storage.ts"),
        ...ownersFor(["lstat"], "git/target-placement.ts"),
        { source: "akuma/identity.ts", symbols: ["mkdir", "writeFile"] },
        { source: "akuma/requests.ts", symbols: ["access", "readFile"] },
        { source: "akuma/request-serve.ts", symbols: ["access", "mkdir", "readFile", "readdir", "rm"] },
        { source: "akuma/request-wire.ts", symbols: ["rename", "rm", "writeFile"] },
        { source: "alias/index.ts", symbols: ["lstat", "mkdir", "readFile", "unlink"] },
        { source: "library/akuma-creation.ts", symbols: ["realpath", "stat"] },
        { source: "library/nuke.ts", symbols: ["rmdir"] },
        { source: "contract-worktree.ts", symbols: ["chmod", "lstat", "readFile", "unlink"] },
        { source: "workspace-place.ts", symbols: ["lstat", "mkdir", "readFile", "unlink"] },
        { source: "coordination/durable-file.ts", symbols: ["lstat", "mkdir", "readFile", "unlink"] },
        { source: "coordination/sqlite-transaction-lock.ts", symbols: ["lstat", "mkdir"] },
        { source: "git/hooks.ts", symbols: ["lstat", "mkdir", "readFile", "unlink"] },
        { source: "git/nuke.ts", symbols: ["access"] },
        { source: "git/reconcile.ts", symbols: ["access", "mkdir", "readdir", "rmdir", "unlink"] },
        { source: "git/tender.ts", symbols: ["access"] },
        { source: "git/workspace.ts", symbols: ["access", "appendFile", "mkdtemp", "readFile", "rm"] },
        { source: "settlement/fence.ts", symbols: ["readdir", "rmdir", "unlink"] },
        { source: "runtime/proc/launch.ts", symbols: ["open"] },
        { source: "runtime/proc/run.ts", symbols: ["FileHandle", "open"] },
        { source: "task/context.ts", symbols: ["lstat", "mkdir", "readFile"] },
        { source: "task/store.ts", symbols: ["lstat", "mkdir", "readFile", "readdir", "unlink"] },
      ],
    },
    { module: "fs/promises", owners: [] },
    {
      module: "node:crypto",
      owners: [
        ...ownersFor(
          ["randomBytes"],
          "coordination/durable-file.ts",
          "git/scratch.ts",
          "library/bind.ts",
          "protocol/attempt.ts",
          "task/context.ts",
          "task/store.ts",
          "akuma/identity.ts",
        ),
        ...ownersFor(
          ["createHash"],
          "cli/draft.ts",
          "git/identity.ts",
          "git/tree.ts",
          "settlement/fence.ts",
          "settlement/holder.ts",
          "body/keys.ts",
          "dispatch/index.ts",
          "workspace-place.ts",
        ),
        { source: "coordination/sqlite-transaction-lock.ts", symbols: ["randomInt"] },
        ...ownersFor(
          ["randomUUID"],
          "akuma/akuma.ts",
          "akuma/providers/claude/index.ts",
          "akuma/providers/opencode-sdk/index.ts",
          "akuma/requests.ts",
          "akuma/request-wire.ts",
        ),
      ],
    },
    {
      module: "node:sqlite",
      owners: [
        ...ownersFor(["DatabaseSync"], "coordination/sqlite-transaction-lock.ts", "akuma/heart/storage.ts"),
        ...ownersFor(
          ["DatabaseSync"],
          "akuma/heart/soul.ts",
          "akuma/heart/schema.ts",
          "akuma/heart/rows.ts",
          "akuma/heart/request-rows.ts",
          "akuma/heart/timeline.ts",
          "akuma/heart/tells.ts",
        ).map((owner) => ({ ...owner, mode: "type-only" as const })),
      ],
    },
    { module: "crypto", owners: [] },
  ],
  forbiddenSourcePatterns: [
    {
      source: "akuma/providers/index.ts",
      pattern: /^import .*\.\/.*\/index\.js";$/mu,
      detail: "provider resolution imports only the selected adapter at the execution edge",
    },
    ...forbiddenFor("git/read-observation.ts", [
      {
        pattern: /(?:contracts\/|settlement\/task-holders|dispatch\/|decodeJournal|decodeHolder)/u,
        detail: "Git read observation is product-blind; product paths and codecs remain with their owners",
      },
      {
        pattern: /(?:\bclass\b|#[A-Za-z_$])/u,
        detail: "Git decode ownership uses one structural callback capability, not nominal or private-field machinery",
      },
      {
        pattern: /withGitDecodeChannel\s*\(/u,
        detail: "read observations consume their caller's channel and never create a compatibility channel",
      },
    ]),
    {
      source: "git/repository.ts",
      pattern: /symref-(?:update|create|delete)/u,
      detail: "admission assertions never change symbolic refs or caller-owned checkout state",
    },
    {
      source: "kanshi/read.ts",
      pattern: /(?:\.snapshot\b|\.readBlobs\s*\(|\.resolveRef\s*\()/u,
      detail: "Kanshi composes owner projections and must not inspect or consume Git observation mechanics",
    },
    ...forbiddenFor("akuma/heart/index.ts", [
      {
        pattern: /\b(?:SELECT|INSERT|UPDATE|DELETE)\b/iu,
        detail: "Heart SQL belongs to schema mechanics or named fact statements, never the transaction judge",
      },
      {
        pattern: /\.prepare\s*\(/u,
        detail: "Heart index owns adjudication and must execute SQL through schema.ts or rows.ts",
      },
    ]),
  ],
  forbiddenModules: ["better-sqlite3", "sqlite3"],
  capabilityRules: [
    { capability: "dynamic-import-nonliteral", owners: [] },
    { capability: "eval", owners: [] },
    { capability: "function-constructor", owners: [] },
    { capability: "math-random", owners: [] },
    { capability: "module-mutable-state", owners: [] },
    { capability: "date-now", owners: ["protocol/attempt.ts", "cli/draft.ts"] },
    {
      capability: "new-date-current",
      owners: [
        "akuma/akuma.ts",
        "akuma/nuke.ts",
        "akuma/body.ts",
        "akuma/publication.ts",
        "dispatch/index.ts",
        "kanshi/read.ts",
        "protocol/bind.ts",
        "protocol/operations.ts",
        "protocol/read/status.ts",
        "task/compose.ts",
        "task/operations.ts",
      ],
    },
    {
      capability: "process-argv",
      owners: [
        "akuma-body.ts",
        "akuma/body.ts",
        "cli/main.ts",
        "cli/index.ts",
        "git/hooks.ts",
        "scripts/check-architecture.ts",
        "scripts/model-change-impact.ts",
      ],
    },
    {
      capability: "process-cwd",
      owners: [
        "akuma/akuma.ts",
        "git/repository.ts",
        "cli/main.ts",
        "cli/runtime.ts",
        "kanshi/read.ts",
        "library/repo.ts",
        "task/index.ts",
        "scripts/check-architecture.ts",
        "scripts/model-change-impact.ts",
      ],
    },
    {
      capability: "process-environment",
      owners: [
        "akuma-body.ts",
        "akuma/body.ts",
        "akuma/providers/acp/core.ts",
        "akuma/providers/claude/index.ts",
        "akuma/providers/codex-app-server/index.ts",
        "akuma/providers/opencode-sdk/session.ts",
        "akuma/requests.ts",
        "cli/invoke.ts",
        "cli/main.ts",
        "cli/runtime.ts",
        "git/process.ts",
        "protocol/audit.ts",
        "protocol/completion.ts",
        "protocol/deliver.ts",
        "runtime/proc/**",
      ],
    },
    {
      capability: "process-output",
      owners: [
        "akuma-body.ts",
        "cli/main.ts",
        "cli/runtime.ts",
        "cli/index.ts",
        "scripts/check-architecture.ts",
        "scripts/model-change-impact.ts",
      ],
    },
    { capability: "process-pid", owners: ["runtime/proc/**"] },
    { capability: "require", owners: [] },
    {
      capability: "type-error-construction",
      owners: [
        "world.ts",
        "akuma-body.ts",
        "akuma/allowed.ts",
        "akuma/akuma.ts",
        "akuma/body.ts",
        "akuma/body-turn.ts",
        "akuma/identity.ts",
        "akuma/archetype.ts",
        "akuma/provider.ts",
        "akuma/provider-recipe.ts",
        "akuma/providers/index.ts",
        "akuma/providers/acp/config.ts",
        "akuma/providers/acp/index.ts",
        "akuma/providers/grok-build/index.ts",
        "akuma/providers/pi/index.ts",
        "alias/index.ts",
        "body/**",
        "cli/actor.ts",
        "contract-worktree.ts",
        "workspace-place.ts",
        "git/hooks.ts",
        "kanshi/**",
        "library/configuration.ts",
        "library/contract.ts",
        "library/input.ts",
        "library/repo.ts",
        "library/akuma-creation.ts",
        "library/address.ts",
        "library/fleet.ts",
        "library/catalog.ts",
        "identity/coordinates.ts",
        "identity/selector.ts",
        "settings.ts",
        "task/**",
      ],
    },
  ],
  forbiddenFileNames: [
    "approval-preparation.ts",
    "claim.ts",
    "forfeit.ts",
    "open.ts",
    "petition-preparation.ts",
    "petition.ts",
    "pipeline.ts",
    "renew.ts",
    "seal.ts",
  ],
  forbiddenDeclarations: [
    /(?:Open|Seal|Renew|Petition|Claim|Forfeit)(?:Data|Entry|Input|Refusal|Decision|Offer|State|Result)$/,
  ],
  verbDirectory: "core/verbs/",
  providerSdkRoots: [
    { module: "@agentclientprotocol/sdk", root: "akuma/providers/acp" },
    { module: "@anthropic-ai/claude-agent-sdk", root: "akuma/providers/claude" },
    { module: "@earendil-works/pi-coding-agent", root: "akuma/providers/pi" },
    { module: "@opencode-ai/sdk", root: "akuma/providers/opencode-sdk" },
  ],
  runtimeGraphRoots: ["cli/parse.ts"],
} as const satisfies ArchitecturePolicy;
