import { any, factErrors, factTypes, gitRepository, types } from "./policy-helpers.js";
export const akumaZones = [
  {
    source: "akuma/heart/facts.ts",
    allow: [
      types("akuma/identity.ts"),
      types("akuma/coordinate.ts"),
      types("akuma/provider-recipe.ts"),
      types("akuma/allowed.ts"),
      types("task/mutation.ts"),
    ],
  },
  { source: "akuma/heart/schema.ts", allow: [] },
  { source: "akuma/coordinate.ts", allow: [] },
  {
    source: "akuma/heart/rows.ts",
    allow: [types("akuma/heart/facts.ts"), types("akuma/provider-recipe.ts"), any("akuma/coordinate.ts")],
  },
  {
    source: "akuma/heart/request-rows.ts",
    allow: [
      types("akuma/heart/facts.ts"),
      types("akuma/identity.ts"),
      any("task/mutation.ts", ["isTaskMutationAction"]),
    ],
  },
  { source: "akuma/heart/tells.ts", allow: [types("akuma/heart/facts.ts")] },
  {
    source: "akuma/heart/timeline.ts",
    allow: [
      types("akuma/heart/facts.ts"),
      any("akuma/heart/rows.ts", [
        "decodeActivityRow",
        "decodeCallRow",
        "decodeTurnRow",
        "ActivityFact",
        "ActivityRow",
        "CallRow",
        "TurnRow",
      ]),
      any("akuma/heart/tells.ts", ["decodeTellAtSequence", "pendingTellProtectionSql", "pendingTellSequencesSql"]),
    ],
  },
  {
    source: "akuma/heart/soul.ts",
    allow: [
      any("akuma/allowed.ts"),
      any("akuma/identity.ts", ["parseAkuId", "AkuId"]),
      any("akuma/provider-recipe.ts"),
      types("akuma/heart/facts.ts"),
    ],
  },
  {
    source: "akuma/heart/storage.ts",
    allow: [
      types("akuma/identity.ts"),
      types("akuma/heart/facts.ts"),
      any("akuma/heart/schema.ts"),
      any("akuma/heart/rows.ts"),
      any("akuma/heart/soul.ts"),
      any("akuma/heart/tells.ts", ["insertTellFact"]),
      any("akuma/heart/timeline.ts", ["pruneActivityFacts"]),
    ],
  },
  {
    source: "akuma/heart/request-authority.ts",
    allow: [
      any("akuma/allowed.ts"),
      types("akuma/identity.ts"),
      types("akuma/heart/facts.ts"),
      any("akuma/heart/request-rows.ts"),
      any("akuma/heart/soul.ts", ["soulFact"]),
      any("akuma/heart/storage.ts"),
    ],
  },
  {
    source: "akuma/heart/index.ts",
    allow: [
      types("akuma/identity.ts"),
      types("akuma/coordinate.ts"),
      any("akuma/heart/facts.ts"),
      any("akuma/heart/request-authority.ts"),
      any("akuma/heart/rows.ts"),
      any("akuma/heart/soul.ts", ["soulFact"]),
      any("akuma/heart/tells.ts"),
      any("akuma/heart/timeline.ts"),
      any("akuma/heart/storage.ts"),
    ],
  },
  {
    source: "akuma/provider.ts",
    allow: [types("akuma/heart/index.ts"), any("akuma/coordinate.ts"), types("akuma/provider-recipe.ts")],
  },
  {
    source: "akuma/projection.ts",
    allow: [types("akuma/heart/index.ts"), any("akuma/provider.ts"), any("akuma/projection-read.ts")],
  },
  { source: "akuma/projection-read.ts", allow: [types("akuma/projection.ts")] },
  {
    source: "akuma/providers/index.ts",
    allow: [
      types("akuma/provider.ts"),
      any("akuma/provider-recipe.ts"),
      any("akuma/providers/acp/config.ts"),
      any("akuma/providers/acp/index.ts"),
      any("akuma/providers/claude/index.ts"),
      any("akuma/providers/codex-app-server/index.ts"),
      any("akuma/providers/grok-build/index.ts"),
      any("akuma/providers/opencode-sdk/index.ts"),
      any("akuma/providers/pi/index.ts"),
    ],
  },
  {
    source: "akuma/providers/claude/index.ts",
    allow: [
      any("akuma/abort.ts"),
      any("akuma/provider.ts"),
      any("akuma/provider-recipe.ts", ["ProviderOptions", "providerLaunchEnv"]),
      any("akuma/providers/claude/events.ts"),
      any("akuma/providers/claude/input.ts"),
    ],
  },
  {
    source: "akuma/providers/pi/index.ts",
    allow: [
      any("akuma/abort.ts"),
      any("akuma/providers/pi/events.ts"),
      any("akuma/provider.ts"),
      types("akuma/provider-recipe.ts"),
      types("akuma/coordinate.ts"),
    ],
  },
  {
    source: "akuma/providers/pi/events.ts",
    allow: [any("akuma/provider.ts"), any("akuma/providers/unified-patch.ts")],
  },
  {
    source: "akuma/providers/codex-app-server/index.ts",
    allow: [
      any("akuma/providers/codex-app-server/events.ts"),
      any("akuma/provider.ts"),
      any("akuma/provider-recipe.ts", ["ProviderExecution", "ProviderOptions", "providerLaunchEnv"]),
      any("runtime/proc/line-rpc.ts"),
    ],
  },
  {
    source: "akuma/providers/acp/core.ts",
    allow: [
      any("akuma/abort.ts"),
      any("akuma/providers/acp/events.ts"),
      any("akuma/provider.ts"),
      any("akuma/provider-recipe.ts", ["providerLaunchEnv"]),
      any("runtime/proc/stdio.ts"),
    ],
  },
  { source: "akuma/providers/acp/config.ts", allow: [types("akuma/provider-recipe.ts", ["SystemPromptMode"])] },
  {
    source: "akuma/providers/acp/index.ts",
    allow: [
      types("akuma/provider.ts"),
      types("akuma/provider-recipe.ts"),
      any("akuma/providers/acp/config.ts"),
      any("akuma/providers/acp/core.ts"),
    ],
  },
  {
    source: "akuma/providers/grok-build/index.ts",
    allow: [types("akuma/provider.ts"), types("akuma/provider-recipe.ts"), any("akuma/providers/acp/core.ts")],
  },
  {
    source: "akuma/providers/codex-app-server/events.ts",
    allow: [any("akuma/provider.ts"), any("akuma/providers/unified-patch.ts"), types("runtime/proc/line-rpc.ts")],
  },
  {
    source: "akuma/providers/opencode-sdk/index.ts",
    allow: [
      any("akuma/abort.ts"),
      any("akuma/providers/opencode-sdk/events.ts"),
      any("akuma/providers/opencode-sdk/session.ts"),
      any("akuma/provider.ts"),
      types("akuma/heart/index.ts"),
      types("akuma/provider-recipe.ts"),
    ],
  },
  {
    source: "akuma/providers/opencode-sdk/session.ts",
    allow: [
      any("akuma/abort.ts"),
      types("akuma/heart/index.ts"),
      any("akuma/provider-recipe.ts", ["ProviderExecution", "providerLaunchEnv"]),
      any("runtime/proc/run.ts"),
    ],
  },
  {
    source: "akuma/providers/**",
    allow: [
      types("akuma/heart/index.ts"),
      any("akuma/provider.ts"),
      types("akuma/provider-recipe.ts"),
      any("runtime/proc/line-rpc.ts"),
    ],
  },
  {
    source: "akuma/archetype.ts",
    allow: [
      any("akuma/allowed.ts"),
      any("akuma/identity.ts"),
      types("akuma/provider.ts", ["ProviderAdapter"]),
      any("akuma/provider-recipe.ts"),
      any("akuma/providers/index.ts", ["resolveProviderExecution"]),
      types("settings.ts"),
    ],
  },
  {
    source: "akuma/publication.ts",
    allow: [any("akuma/abort.ts"), any("akuma/heart/index.ts"), any("akuma/identity.ts"), any("runtime/proc/run.ts")],
  },
  {
    source: "akuma/request-wire.ts",
    allow: [
      any("akuma/allowed.ts", ["decodeAllowedActions"]),
      any("akuma/identity.ts", ["archetypeName", "parseAkuId", "AkuId"]),
      any("akuma/provider-recipe.ts", ["decodeProviderOptions", "decodeReadonlyRestraint", "ReadonlyRestraint"]),
      any("akuma/providers/index.ts", ["decodeProviderExecution"]),
      any("task/mutation.ts", [
        "TaskMutationAction",
        "TaskMutationRequest",
        "decodeTaskMutationRequest",
        "isTaskMutationAction",
      ]),
    ],
  },
  {
    source: "akuma/requests.ts",
    allow: [
      any("akuma/abort.ts", ["abortableDelay"]),
      any("akuma/provider.ts", ["AKUMA_REQUESTS_ENV"]),
      any("akuma/request-wire.ts", [
        "absolute",
        "atomicJson",
        "decodeReceipt",
        "receiptPath",
        "requestPath",
        "requestPayload",
        "CallRequestClaim",
        "DeliverRequestClaim",
        "ForwardedDeliveryReference",
        "ForwardedReviewReference",
        "KillRequestClaim",
        "RequestClaim",
        "RequestReceipt",
        "ReviewRequestClaim",
        "TellRequestClaim",
        "UpstreamRequestOutcome",
        "WaitRequestClaim",
      ]),
      any("task/mutation.ts", ["TaskMutationRequest", "isTaskMutationAction"]),
    ],
  },
  {
    source: "akuma/request-serve.ts",
    allow: [
      any("akuma/abort.ts", ["abortableDelay"]),
      any("akuma/heart/index.ts", [
        "HeldAkumaLeash",
        "admitRequest",
        "readNonterminalRequests",
        "readRequest",
        "readSoul",
        "refuseRequest",
        "reserveRequest",
        "serveRequest",
        "serveUpstreamRequest",
        "voidRequest",
        "KillEvidence",
        "RequestFact",
        "Soul",
        "UpstreamRequestService",
      ]),
      any("akuma/identity.ts", ["pathsForAkuId", "worldRootForAkumaPaths", "AkuId", "AkumaPaths"]),
      any("akuma/publication.ts", ["BIRTH_TIMEOUT_MS", "publishAkuma"]),
      any("akuma/request-wire.ts", [
        "atomicJson",
        "canonicalAkuId",
        "decodeClaim",
        "decodeRecipe",
        "receiptPath",
        "RequestReceipt",
        "StructuralRequestClaim",
        "TaskRequestClaim",
        "UpstreamRequestFailure",
        "UpstreamRequestOutcome",
      ]),
      any("task/mutation.ts", ["TaskMutationRequest", "isTaskMutationAction"]),
      any("akuma/request-execution.ts", ["executeRequest"]),
    ],
  },
  {
    source: "akuma/request-execution.ts",
    allow: [
      types("akuma/identity.ts", ["AkuId"]),
      types("akuma/heart/index.ts", ["UpstreamRequestService"]),
      types("akuma/request-wire.ts", ["TaskRequestClaim"]),
      types("akuma/request-serve.ts", ["ServeInput", "UpstreamFact"]),
    ],
  },
  {
    source: "akuma/body.ts",
    allow: [
      any("akuma/abort.ts"),
      any("akuma/heart/index.ts"),
      types("akuma/identity.ts"),
      any("akuma/body-supervisor.ts", ["BodySupervisor", "CONTROL_RESPONSE_MS"]),
      any("akuma/turn-drive.ts", ["driveTurn", "DrivenTurn", "turnRecipe"]),
      types("akuma/provider.ts", ["ProviderAdapter"]),
      any("akuma/providers/index.ts"),
      any("akuma/request-serve.ts", [
        "clearBodyRequestTransport",
        "settleBodyRequests",
        "UpstreamExecutionPort",
        "RequestChildLaunch",
      ]),
      any("runtime/proc/run.ts"),
    ],
  },
  {
    source: "akuma/body-supervisor.ts",
    allow: [
      any("akuma/abort.ts", ["abortableDelay"]),
      any("akuma/heart/index.ts", ["heartExists", "readHeart", "HeartSnapshot", "HeldAkumaLeash"]),
      types("akuma/identity.ts", ["AkumaPaths"]),
    ],
  },
  {
    source: "akuma/turn-drive.ts",
    allow: [
      any("akuma/abort.ts", ["abortableDelay"]),
      any("akuma/heart/index.ts", [
        "appendActivity",
        "beginTurn",
        "breakBody",
        "heartExists",
        "readHeart",
        "recordSession",
        "recordTellDeliveries",
        "recordTellReceipt",
        "HeartSnapshot",
        "HeldAkumaLeash",
        "ResumeCoordinate",
        "Soul",
        "TellFact",
      ]),
      types("akuma/identity.ts"),
      any("akuma/provider.ts", ["AgentEvent", "encodeAgentEvent", "ProviderAdapter", "Session", "TurnResult"]),
      any("akuma/request-serve.ts", ["BodyRequestPump", "RequestChildLaunch", "UpstreamExecutionPort"]),
      any("akuma/body-supervisor.ts", ["BodySupervisor", "CONTROL_RESPONSE_MS"]),
    ],
  },
  {
    source: "akuma/akuma.ts",
    allow: [
      any("akuma/allowed.ts"),
      any("akuma/akuma-errors.ts", ["AkumaNotBornError"]),
      any("akuma/akuma-handle.ts", ["AkumaHandle", "akumaCallExecution", "LastAnswer"]),
      any("akuma/akuma-observe.ts", [
        "bornStatus",
        "fleetListRow",
        "readAkumaBirthCwd",
        "readBudgetedStatus",
        "BudgetedStatusObservation",
      ]),
      any("akuma/akuma-product-symbols.ts", ["CALL_WITH_CONTEXT"]),
      any("akuma/akuma-product.ts", ["Akuma", "callAkumaWithContext"]),
      any("akuma/body.ts"),
      any("akuma/projection.ts"),
      any("akuma/heart/index.ts"),
      any("akuma/identity.ts"),
      any("akuma/archetype.ts"),
      any("akuma/publication.ts"),
      types("akuma/provider-recipe.ts", ["ReadonlyRestraint"]),
      any("akuma/providers/index.ts"),
      any("akuma/requests.ts"),
      any("settings.ts"),
      types("world.ts"),
    ],
  },
  {
    source: "akuma/akuma-observe.ts",
    allow: [
      types("akuma/akuma.ts", ["AkumaListRow", "AkumaStatus", "UnbornAkumaListRow"]),
      any("akuma/akuma-errors.ts", ["AkumaNotBornError"]),
      any("akuma/heart/index.ts"),
      any("akuma/identity.ts"),
      any("akuma/projection.ts"),
      any("akuma/providers/index.ts"),
      types("world.ts"),
    ],
  },
  {
    source: "akuma/akuma-handle.ts",
    allow: [
      any("akuma/body.ts", ["CONTROL_RESPONSE_MS", "TellResult", "wakeRecordedTell", "spawnAkumaBody"]),
      any("akuma/heart/index.ts"),
      any("akuma/identity.ts"),
      any("akuma/projection.ts"),
      any("akuma/providers/index.ts"),
      any("akuma/publication.ts"),
      any("akuma/akuma-observe.ts", ["bornStatus"]),
      any("akuma/akuma-errors.ts", ["AkumaNotBornError"]),
      types("akuma/akuma.ts", ["AkumaCallExecution", "AkumaStatus", "ForkReceipt", "InterruptReceipt"]),
      types("world.ts"),
    ],
  },
  { source: "akuma/akuma-product-symbols.ts", allow: [] },
  { source: "akuma/akuma-errors.ts", allow: [types("akuma/identity.ts", ["AkuId"])] },
  {
    source: "akuma/akuma-product.ts",
    allow: [
      any("akuma/akuma-handle.ts", ["AkumaHandle"]),
      types("akuma/akuma.ts", [
        "AkumaCallContext",
        "AkumaCallInput",
        "AkumaConfiguration",
        "AkumaList",
        "AkumaListInput",
      ]),
      any("akuma/akuma-product-symbols.ts", ["CALL_WITH_CONTEXT"]),
      any("akuma/akuma-observe.ts", ["fleetListRow", "readAkumaBirthCwd"]),
      any("akuma/identity.ts"),
      any("akuma/archetype.ts"),
      any("akuma/publication.ts"),
      any("akuma/body.ts"),
      any("akuma/requests.ts"),
      any("akuma/allowed.ts"),
      any("settings.ts"),
      types("world.ts"),
    ],
  },
  {
    source: "akuma/nuke.ts",
    allow: [
      any("akuma/body.ts", ["CONTROL_RESPONSE_MS"]),
      any("akuma/heart/index.ts", ["HeldAkumaLeash", "readHeart", "readKill", "requestStop"]),
      any("akuma/identity.ts", ["akuIdFromDirectoryName", "akumaPaths", "akumaRunRoot", "AkuId", "AkumaPaths"]),
      any("alias/index.ts", ["nukeAliases"]),
      types("world.ts", ["WorldRoot"]),
    ],
  },
  {
    source: "akuma/index.ts",
    allow: [
      any("akuma/allowed.ts"),
      any("akuma/akuma.ts"),
      any("akuma/archetype.ts"),
      any("akuma/requests.ts"),
      any("akuma/heart/index.ts", ["readSoul"]),
      types("akuma/heart/index.ts"),
      any("akuma/identity.ts", ["pathsForAkuId", "AkuId"]),
      types("akuma/provider.ts"),
      types("akuma/provider-recipe.ts"),
      types("world.ts"),
    ],
  },
  {
    source: "dispatch/index.ts",
    allow: [
      any("akuma/identity.ts", ["parseAkuId", "AkuId"]),
      any("coordination/sqlite-transaction-lock.ts"),
      factErrors,
      factTypes,
      any("git/read-observation.ts"),
      gitRepository,
      any("git/repository.ts"),
    ],
  },
  {
    source: "alias/index.ts",
    allow: [
      any("akuma/identity.ts", ["parseAkuId", "AkuId"]),
      any("coordination/durable-file.ts"),
      any("coordination/sqlite-transaction-lock.ts"),
      factErrors,
      any("identity/selector.ts"),
      types("world.ts"),
    ],
  },
];
