/* eslint-disable max-lines -- Runtime Library dependency policy is one coherent ownership boundary. */
import { any, factErrors, factTypes, gitRepository, types } from "./policy-helpers.js";
export const runtimeLibraryZones = [
  { source: "runtime/proc/lifecycle.ts", allow: [] },
  { source: "runtime/proc/process-exit.ts", allow: [types("runtime/proc/types.ts")] },
  { source: "runtime/proc/termination.ts", allow: [] },
  { source: "runtime/proc/types.ts", allow: [] },
  {
    source: "runtime/proc/windows-run.ts",
    allow: [
      any("runtime/proc/launch.ts"),
      any("runtime/proc/process-exit.ts"),
      any("runtime/proc/termination.ts"),
      any("runtime/proc/lifecycle.ts"),
      types("runtime/proc/types.ts"),
    ],
  },
  { source: "runtime/proc/line-rpc.ts", allow: [any("runtime/proc/stdio.ts")] },
  { source: "runtime/proc/stdio.ts", allow: [any("runtime/proc/run.ts"), any("runtime/proc/launch.ts")] },
  {
    source: "runtime/proc/run.ts",
    allow: [
      any("runtime/proc/launch.ts"),
      any("runtime/proc/process-exit.ts"),
      any("runtime/proc/termination.ts"),
      any("runtime/proc/lifecycle.ts"),
      types("runtime/proc/types.ts"),
      any("runtime/proc/windows-run.ts"),
    ],
  },
  { source: "runtime/proc/launch.ts", allow: [] },
  {
    source: "verification/declaration.ts",
    allow: [types("core/decide.ts"), any("core/facts/types.ts", ["ContractId", "DocumentSegmentKey", "Gate", "gate"])],
  },
  {
    source: "verification/execution.ts",
    allow: [
      types("core/facts/types.ts"),
      any("git/hooks.ts"),
      any("library/configuration.ts", ["worktreeHooksFrom"]),
      types("git/scratch.ts"),
      gitRepository,
      types("settings.ts"),
      any("runtime/proc/run.ts"),
      types("verification/declaration.ts"),
    ],
  },
  {
    source: "library/bind.ts",
    allow: [
      any("body/decode.ts", ["decodeContractDocument"]),
      any("core/facts/errors.ts", ["AuthorityCorruptionError"]),
      any("contract-worktree.ts"),
      factTypes,
      types("git/read-observation.ts", ["GitDecodeChannel"]),
      any("identity/normalize.ts", ["fitIdentityStem", "normalizeIdentityStem"]),
      any("protocol/operations.ts", ["IntentOutcome", "RepositoryScope", "stateOperation"]),
      any("protocol/bind.ts", ["BindTargetSelection", "bindOperation"]),
      any("settlement/holder.ts", ["claimTaskHolder", "claimTaskHolderWithFence"]),
      types("task/identity.ts", ["TaskId"]),
      types("verification/declaration.ts", ["VerificationDeclarationPreparation"]),
      any("library/refusal.ts", ["KeiyakuRefusal", "KeiyakuRefused"]),
      any("library/input.ts", ["contractTerms", "documentDerivation"]),
    ],
  },
  {
    source: "library/contract-bind.ts",
    allow: [
      any("body/decode.ts", ["decodeContractDocument"]),
      any("core/facts/types.ts", ["contractId", "ContractId"]),
      any("git/read-observation.ts", ["withGitDecodeChannel"]),
      any("library/bind.ts", ["admitForkBindWithAppointment", "prepareMarkdownBind"]),
      any("library/input.ts", [
        "actorOption",
        "normalizedGates",
        "normalizedList",
        "requireInput",
        "requireMarkdown",
        "taskOption",
      ]),
      any("library/mutation.ts", ["completionInput", "completeHolderMutation", "completeMutation", "MutationResult"]),
      any("library/refusal.ts", ["requireAccepted"]),
      any("library/region.ts", ["observeRegion", "RegionObservation"]),
      any("library/repo.ts", ["Repo", "scopeForRepo"]),
      any("library/configuration.ts", ["worktreeHooksOption", "WorktreeHooks"]),
      any("protocol/operations.ts", ["RepositoryScope", "withScopeAbortSignal"]),
    ],
  },
  {
    source: "library/contract-operations.ts",
    allow: [
      any("akuma/request-rendezvous.ts", ["requestBodyCommand"]),
      any("akuma/request-wire.ts", ["eraseRequestCommand", "ErasedRequestCommand", "RequestCommand"]),
      any("core/facts/types.ts", ["contractId", "ContractId"]),
      any("library/contract-forwarding.ts", [
        "executeLocalDelivery",
        "executeLocalReview",
        "executeForwardedAudit",
        "executeForwardedDeliver",
        "executeForwardedReview",
        "AttestationVerdict",
        "DeliveryExecutionInput",
        "Review",
        "ReviewExecutionInput",
      ]),
      any("library/contract-forwarding-result.ts", [
        "auditReportSchema",
        "auditResultSchema",
        "decodeContractLiveFailure",
        "deliveryResultSchema",
        "encodeContractLiveFailure",
        "reviewResultSchema",
      ]),
      types("protocol/audit.ts", ["AuditReport"]),
      types("protocol/deliver.ts", ["IntegrationConflictMaterialized"]),
      types("library/delivery.ts", ["DeliveryValue"]),
      types("library/mutation.ts", ["MutationResult"]),
    ],
  },
  {
    source: "library/contract-types.ts",
    allow: [
      types("core/facts/types.ts", ["ContractId", "JournalEntry", "SnapshotId"]),
      types("contract-worktree.ts", ["ContractFileEffect", "ContractFileLag"]),
      types("protocol/reconcile.ts", ["ReconcileReport"]),
      types("dispatch/index.ts", ["Dispatch"]),
      types("library/configuration.ts", ["Gate", "WorktreeHooks"]),
      types("library/region.ts", ["AmendRegionObservation", "RegionObservation"]),
      types("library/repo.ts", ["Repo"]),
      types("library/mutation.ts", ["MutationResult"]),
      types("settlement/settle.ts", ["SettlementReport"]),
      types("library/contract.ts", ["Keiyaku", "AttestationVerdict"]),
      types("task/identity.ts", ["TaskId"]),
    ],
  },
  {
    source: "library/audit.ts",
    allow: [
      any("body/decode.ts", ["decodeContractDocument"]),
      types("core/facts/types.ts"),
      any("git/read-observation.ts", ["withGitDecodeChannel"]),
      any("protocol/audit.ts", ["auditOperation", "AuditReport"]),
      any("protocol/operations.ts", ["RepositoryScope", "withScopeAbortSignal"]),
      any("library/configuration.ts", ["worktreeHooksOption", "WorktreeHooks"]),
      any("library/input.ts", [
        "actorOption",
        "documentDerivation",
        "optionalBoolean",
        "optionalSignal",
        "requireInput",
      ]),
      any("library/mutation.ts", ["completeMutation", "MutationResult"]),
      any("library/refusal.ts", ["requireAccepted"]),
    ],
  },
  {
    source: "library/delivery.ts",
    allow: [
      types("core/facts/types.ts"),
      types("protocol/deliver.ts", ["DeliverValue"]),
      types("library/continuation.ts", ["ContinuationReport"]),
    ],
  },
  {
    source: "library/continuation.ts",
    allow: [
      types("core/facts/types.ts", ["ActorId", "ContractId", "ContractState", "JournalEntry"]),
      any("git/observe.ts", ["observeActiveContractWorld"]),
      any("git/reconcile.ts", ["reconcileDependentWorktree"]),
      types("git/reconcile.ts", ["ReconcileResult"]),
      any("git/read-observation.ts", ["GitDecodeChannel", "withGitReadObservation"]),
      any("git/workspace.ts", ["worktreePath"]),
      any("protocol/deliver.ts", ["continueDeliveryOperation"]),
      any("protocol/operations.ts", ["DocumentDerivation", "PlacementStop", "RepositoryScope"]),
      types("library/mutation.ts", ["AcceptedIntent"]),
      any("workspace-place.ts", ["appointmentFor", "readPlaceRegister"]),
    ],
  },
  {
    source: "library/mutation.ts",
    allow: [
      types("core/facts/types.ts"),
      any("git/read-observation.ts", ["GitDecodeChannel", "withGitDecodeChannel"]),
      types("protocol/operations.ts", ["IntentOutcome", "RepositoryScope"]),
      types("protocol/reconcile.ts", ["ReconcileReport"]),
      types("protocol/outcome.ts", ["AcceptedObligations"]),
      types("settlement/holder.ts", ["TaskHolderAdmission"]),
      any("settlement/settle.ts", ["deferredTaskHolderSettlement", "SettlementReport"]),
      types("library/configuration.ts", ["WorktreeHooks"]),
      any("library/reconcile.ts", ["completeReconcile", "ReconcileCompletion"]),
    ],
  },
  {
    source: "library/reconcile.ts",
    allow: [
      any("contract-worktree.ts", ["projectContractWorktree", "ContractFileEffect", "ContractFileLag"]),
      any("workspace-place.ts", [
        "appointManagedWorktrees",
        "placeRegisterPath",
        "PlaceRegister",
        "releaseManagedWorktrees",
      ]),
      types("core/facts/types.ts"),
      any("core/facts/errors.ts", ["AuthorityCorruptionError"]),
      types("git/read-observation.ts", ["GitDecodeChannel"]),
      any("protocol/reconcile.ts", [
        "reconcileAllOperation",
        "reconcileOperation",
        "worldContractStates",
        "ReconcileReport",
      ]),
      any("git/reconcile.ts", ["reconcileObservationFailure"]),
      any("protocol/operations.ts", ["stateOperation", "RepositoryScope"]),
      any("settlement/settle.ts", ["settle", "settleAll", "SettlementReport"]),
      types("library/configuration.ts", ["WorktreeHooks"]),
    ],
  },
  {
    source: "library/refusal.ts",
    allow: [
      types("core/facts/types.ts", ["ContractId"]),
      types("protocol/operations.ts", ["IntentOutcome", "IntentRefusal", "IntentRetry"]),
      types("library/mutation.ts", ["AcceptedIntent"]),
    ],
  },
  {
    source: "library/repo.ts",
    allow: [
      any("protocol/operations.ts"),
      any("git/repository.ts", ["NoGitWorldError"]),
      any("git/read-observation.ts", ["withGitDecodeChannel"]),
      any("library/configuration.ts"),
      any("library/input.ts"),
      any("library/reconcile.ts", ["completeRepoReconcile", "RepoContractReconcileReport", "RepoReconcileReport"]),
    ],
  },
  {
    source: "library/keiyaku.ts",
    allow: [
      types("akuma/allowed.ts"),
      types("akuma/identity.ts"),
      types("alias/index.ts"),
      factErrors,
      types("core/facts/types.ts"),
      types("dispatch/index.ts"),
      types("identity/selector.ts"),
      any("library/contract.ts"),
      any("library/repo.ts"),
      any("library/configuration.ts"),
      any("library/akuma-creation.ts"),
      any("library/composition.ts", ["composeLibrary"]),
      any("akuma/requests.ts"),
      any("library/fleet.ts"),
      any("library/catalog.ts"),
      any("library/address.ts"),
      any("library/nuke.ts"),
      types("library/refusal.ts", ["NukeConfirmationRefusal", "NukeConfirmationRequiredRefusal"]),
      types("library/region.ts"),
      types("settlement/settle.ts"),
      types("world.ts"),
    ],
  },
  {
    source: "library/composition.ts",
    allow: [
      any("library/contract.ts", ["KeiyakuHandle", "bindKeiyaku", "keiyakuOf", "listKeiyaku", "observeKeiyaku"]),
      any("library/akuma-creation.ts", ["callKeiyaku", "forkKeiyaku"]),
      any("library/fleet.ts", ["historyAkuma", "interruptAkuma", "killAkuma", "statusAkuma", "tellAkuma", "waitAkuma"]),
      any("library/catalog.ts", ["listCatalog"]),
      any("library/nuke.ts", ["nukeKeiyaku"]),
      any("akuma/requests.ts", ["executionChannel", "localExecutionContext", "ExecutionContext"]),
    ],
  },
  {
    source: "library/nuke.ts",
    allow: [
      any("akuma/nuke.ts", ["nukeAkuma", "stopAkuma"]),
      any("git/nuke.ts", ["nukeGit"]),
      any("task/operations.ts", ["nukeTask"]),
      any("library/input.ts", ["requireInput", "requireMarkdown"]),
      any("library/refusal.ts", ["KeiyakuRefused"]),
      types("world.ts", ["WorldRoot"]),
    ],
  },
  {
    source: "library/akuma-creation.ts",
    allow: [
      any("alias/index.ts"),
      types("akuma/allowed.ts"),
      any("akuma/akuma.ts"),
      any("akuma/identity.ts"),
      any("akuma/akuma-product.ts", ["beginAkumaCall", "finishAkumaCall", "AkumaBornCall"]),
      any("akuma/requests.ts"),
      any("akuma/identity.ts", ["parseAkuId", "AkuId"]),
      factErrors,
      types("core/facts/types.ts", ["ContractId"]),
      any("dispatch/index.ts"),
      any("identity/selector.ts"),
      any("library/contract.ts", ["Keiyaku", "KeiyakuRefused"]),
      any("library/contract-handle.ts", ["seatForKeiyaku"]),
      any("library/input.ts", ["requireInput"]),
      any("library/address.ts", ["addressAkuma"]),
      any("library/repo.ts", ["Repo", "scopeForRepo"]),
      any("workspace-place.ts", ["readManagedWorktreeAppointment"]),
      types("settings.ts"),
      types("world.ts"),
    ],
  },
  {
    source: "library/address.ts",
    allow: [
      any("alias/index.ts", ["AliasBinding", "readAliases"]),
      any("akuma/akuma.ts", ["Akuma", "AkumaList"]),
      any("akuma/index.ts", ["probeBornAkuma"]),
      any("akuma/identity.ts", ["parseAkuId", "AkuId"]),
      any("core/facts/types.ts", ["contractId"]),
      any("dispatch/index.ts", ["readDispatches"]),
      any("identity/selector.ts"),
      types("kanshi/index.ts"),
      any("library/input.ts", ["requireInput"]),
      any("library/repo.ts", ["Repo", "scopeForRepo"]),
      types("world.ts"),
    ],
  },
  {
    source: "library/fleet.ts",
    allow: [
      any("akuma/index.ts"),
      any("akuma/identity.ts", ["parseAkuId", "parsePublicHistoryId"]),
      any("akuma/akuma.ts", ["readBudgetedStatus", "tellAkumaWithId"]),
      any("akuma/requests.ts"),
      any("akuma/request-wire.ts", ["eraseRequestCommand", "ErasedRequestCommand", "RequestCommand"]),
      types("core/facts/types.ts", ["ContractId"]),
      any("dispatch/index.ts", ["readDispatch"]),
      any("library/address.ts"),
      any("library/fleet-result.ts", [
        "AkumaKillResult",
        "AkumaObservation",
        "AkumaObservationStage",
        "AkumaTellResult",
        "AkumaUnobserved",
        "AkumaWaitResult",
        "CreatedTaskObservation",
        "DispatchAssociation",
        "fleetResultSchemas",
        "isKillResult",
        "isTellResult",
        "isWaitResult",
        "parseAkumaObservation",
        "parseCreatedTaskObservation",
      ]),
      any("library/input.ts", ["requireInput"]),
      any("library/repo.ts", ["Repo", "scopeForRepo"]),
      types("task/index.ts"),
      any("task/operations.ts", ["observeTaskBoard"]),
      types("world.ts"),
    ],
  },
  {
    source: "library/catalog.ts",
    allow: [
      any("akuma/akuma.ts", ["Akuma", "AkumaList"]),
      any("akuma/archetype.ts", ["ArchetypeCatalogRow", "listArchetypeDefinitions"]),
      types("task/index.ts", ["TaskRow"]),
      any("task/catalog.ts", ["observeTaskCatalogRows"]),
      any("library/contract.ts", ["ContractBoard", "listKeiyaku"]),
      any("library/input.ts", ["requireInput"]),
      any("library/repo.ts", ["Repo"]),
      types("world.ts"),
    ],
  },
  {
    source: "library/input.ts",
    allow: [
      any("body/decode.ts", ["verificationDefinition"]),
      types("body/types.ts"),
      any("core/facts/types.ts", ["ActorId", "ContractId", "ContractTerms", "Gate", "actorId", "gate", "gateWord"]),
      any("task/identity.ts", ["parseTaskId", "TaskId"]),
      types("protocol/operations.ts", ["DocumentDerivation"]),
      any("verification/declaration.ts", ["prepareVerificationDeclaration"]),
    ],
  },
  {
    source: "library/configuration.ts",
    allow: [
      any("core/facts/types.ts", ["gateWord"]),
      any("settings.ts", ["Settings", "SettingsError"]),
      types("git/hooks.ts"),
    ],
  },
  {
    source: "library/region.ts",
    allow: [
      any("body/decode.ts"),
      any("body/region.ts"),
      types("core/facts/types.ts"),
      types("protocol/read/documents.ts", ["ContractDocumentProjection"]),
      any("git/read-observation.ts", ["GitDecodeChannel", "withGitDecodeChannel"]),
      any("protocol/operations.ts", ["RepositoryScope", "documentsOperationAt"]),
    ],
  },
  {
    source: "index.ts",
    allow: [any("library/keiyaku.ts"), any("settings.ts"), any("world.ts")],
  },
];
