import { any, factErrors, factTypes, types } from "./policy-helpers.js";

export const contractHandleZones = [
  {
    source: "library/contract-forwarding.ts",
    allow: [
      any("body/decode.ts", ["decodeContractDocument"]),
      any("core/facts/codec.ts", ["encodeEntry"]),
      any("core/facts/types.ts", [
        "changeId",
        "contractHead",
        "contractId",
        "snapshotId",
        "ContractId",
        "ContractState",
        "JournalEntry",
      ]),
      any("git/read-observation.ts", ["withGitDecodeChannel", "GitDecodeChannel"]),
      any("protocol/deliver.ts", ["deliverOperation", "IntegrationConflictMaterialized"]),
      any("protocol/operations.ts", ["RepositoryScope", "withScopeAbortSignal"]),
      any("protocol/review.ts", ["reviewOperation", "ReviewValue"]),
      types("protocol/audit.ts", ["AuditReport"]),
      any("library/audit.ts", ["auditContract", "AuditInput"]),
      any("library/continuation.ts", ["continueAcceptedCompletion", "ContinuationReport"]),
      types("library/configuration.ts", ["WorktreeHooks"]),
      types("library/delivery.ts", ["DeliveryValue"]),
      any("library/input.ts", ["actorOption", "documentDerivation", "invalidInput", "optionalNonblank"]),
      any("library/mutation.ts", ["completionInput", "completeMutation", "MutationResult"]),
      any("library/refusal.ts", [
        "forwardedMutationFailure",
        "KeiyakuRefused",
        "KeiyakuRetry",
        "KeiyakuRefusal",
        "KeiyakuRetryReason",
        "requireAccepted",
      ]),
      any("library/contract-forwarding-result.ts", [
        "ForwardedAuditReceipt",
        "ForwardedDeliveryReceipt",
        "ForwardedMutationReceipt",
        "ForwardedReviewReceipt",
        "Review",
        "isAuditReport",
        "isForwardedAuditReceipt",
        "isForwardedDeliveryReceipt",
        "isForwardedReviewReceipt",
      ]),
      any("library/repo.ts", ["Repo", "scopeForRepo"]),
    ],
  },
  {
    source: "library/contract-forwarding-result.ts",
    allow: [
      any("core/facts/codec.ts", ["encodeEntry"]),
      any("core/facts/types.ts", ["changeId", "contractHead", "contractId", "snapshotId", "JournalEntry"]),
      types("protocol/audit.ts", ["AuditReport"]),
      types("protocol/deliver.ts", ["IntegrationConflictMaterialized"]),
      types("protocol/review.ts", ["ReviewValue"]),
      types("library/continuation.ts", ["ContinuationReport"]),
      types("library/delivery.ts", ["DeliveryValue"]),
      types("library/mutation.ts", ["MutationResult"]),
      types("library/refusal.ts", ["KeiyakuRefusal", "KeiyakuRetryReason"]),
      any("library/contract-forwarding-reconciliation-result.ts", ["reconciliationEffect", "reconciliationLag"]),
    ],
  },
  {
    source: "library/contract-forwarding-reconciliation-result.ts",
    allow: [any("core/facts/types.ts", ["snapshotId"])],
  },
  {
    source: "library/contract.ts",
    allow: [
      any("library/contract-handle.ts", ["KeiyakuHandle"]),
      any("akuma/requests.ts"),
      any("body/amend.ts"),
      any("markdown/diff.ts"),
      any("body/arc.ts"),
      any("body/decode.ts"),
      any("contract-guidance.ts", ["renderContractGuidance"]),
      any("contract-worktree.ts"),
      factErrors,
      factTypes,
      types("protocol/read/status.ts", [
        "AfterEndpointObservation",
        "ContractAfterEdge",
        "ContractBoard",
        "ContractDependent",
        "ContractDisposition",
        "ContractGateCurrent",
        "ContractGateReport",
        "ContractObservation",
        "ContractPhase",
        "ContractRow",
        "ContractWorkspaceObservation",
      ]),
      any("protocol/operations.ts", [
        "contractObservationOperation",
        "contractsOperation",
        "deliveryDiffOperation",
        "deliveryOperation",
        "stateOperation",
        "DeliveryPreparationRefusal",
        "PlacementStop",
        "RepositoryScope",
        "VerificationStop",
      ]),
      any("protocol/abandon.ts", ["abandonOperation"]),
      any("protocol/amend.ts", ["amendOperation"]),
      any("protocol/arc.ts", ["arcOperation"]),
      types("protocol/audit.ts", ["AuditReport"]),
      any("protocol/deliver.ts", ["deliverOperation", "IntegrationConflictMaterialized", "VerificationReuse"]),
      types("protocol/reconcile.ts", ["ReconcileReport"]),
      any("protocol/review.ts", ["reviewOperation", "ReviewValue"]),
      any("dispatch/index.ts", ["Dispatch", "readDispatchesAt"]),
      any("git/identity.ts", ["mintSnapshotId"]),
      any("git/observe.ts", ["observeContractsForAdmissionInObservationAt"]),
      any("git/read-observation.ts", ["GitDecodeChannel", "withGitDecodeChannel", "withGitReadObservation"]),
      any("library/audit.ts", ["auditContract", "AuditInput"]),
      any("library/delivery.ts"),
      any("library/bind.ts", ["admitForkBindWithAppointment", "prepareMarkdownBind"]),
      any("library/refusal.ts"),
      any("library/mutation.ts"),
      any("library/reconcile.ts", ["completeReconcile"]),
      any("library/input.ts"),
      any("library/region.ts"),
      any("library/configuration.ts"),
      any("library/continuation.ts", ["ContinuationReport", "continueAcceptedCompletion"]),
      any("library/repo.ts"),
      any("library/contract-bind.ts", ["bindFromCli", "bindKeiyaku"]),
      types("library/contract-types.ts"),
      any("library/contract-operations.ts", [
        "AttestationVerdict",
        "Review",
        "executeForwardedDeliver",
        "executeForwardedReview",
        "requestForwardedContract",
        "executeLocalDelivery",
        "executeLocalReview",
        "forwardedAuditReceipt",
        "forwardedDeliveryReceipt",
        "forwardedReviewReceipt",
        "requireForwarded",
      ]),
      any("settlement/holder.ts"),
      any("settlement/settle.ts"),
      types("task/identity.ts", ["TaskId"]),
    ],
  },
  {
    source: "library/contract-handle.ts",
    allow: [
      any("akuma/requests.ts"),
      any("body/amend.ts"),
      any("body/arc.ts"),
      any("body/decode.ts"),
      any("contract-guidance.ts", ["renderContractGuidance"]),
      any("core/facts/types.ts"),
      factErrors,
      any("dispatch/index.ts"),
      any("git/identity.ts"),
      any("git/observe.ts"),
      any("git/read-observation.ts"),
      any("library/audit.ts"),
      any("library/configuration.ts"),
      any("library/continuation.ts"),
      any("library/contract-operations.ts"),
      any("library/contract-bind.ts", ["bindFromCli", "bindKeiyaku"]),
      any("library/contract-types.ts"),
      any("library/delivery.ts"),
      any("library/input.ts"),
      any("library/mutation.ts"),
      any("library/reconcile.ts"),
      any("library/refusal.ts"),
      any("library/region.ts"),
      any("library/repo.ts"),
      any("markdown/diff.ts"),
      any("protocol/abandon.ts"),
      any("protocol/amend.ts"),
      any("protocol/arc.ts"),
      any("protocol/audit.ts"),
      any("protocol/deliver.ts"),
      any("protocol/operations.ts"),
      any("protocol/read/status.ts"),
      any("settlement/holder.ts"),
      types("settlement/settle.ts", ["SettlementAction", "SettlementLag", "SettlementReport"]),
      types("task/identity.ts"),
    ],
  },
];
