import { any, types } from "./policy-helpers.js";
export const cliZones = [
  {
    source: "cli/commands/akuma.ts",
    allow: [
      any("akuma/allowed.ts"),
      any("akuma/identity.ts", ["parseAkuId", "AkuId"]),
      any("cli/usage.ts"),
      any("duration.ts"),
      any("identity/selector.ts"),
    ],
  },
  {
    source: "cli/commands/akuma-invoke.ts",
    allow: [
      any("akuma/index.ts"),
      any("library/akuma-creation.ts", ["beginCall", "finishCall"]),
      any("cli/square-edge.ts", ["recognizeAndListen"]),
      any("index.ts"),
      types("cli/commands/akuma.ts"),
      types("settings.ts"),
      types("world.ts"),
    ],
  },
  {
    source: "cli/commands/install.ts",
    allow: [any("cli/usage.ts"), any("runtime/proc/run.ts")],
  },
  {
    source: "cli/commands/task-query.ts",
    allow: [
      types("task/document.ts", ["TaskPriority", "TaskState"]),
      types("task/identity.ts", ["TaskId"]),
      any("task/query.ts", [
        "MAX_TASK_LIMIT",
        "TASK_RELATION_PREDICATE_FIELDS",
        "normalizeTaskQuery",
        "TaskQueryExpression",
        "TaskQueryPredicate",
      ]),
    ],
  },
  {
    source: "cli/commands/task.ts",
    allow: [any("cli/commands/task-query.ts"), any("cli/usage.ts")],
  },
  {
    source: "cli/commands/task-invoke.ts",
    allow: [
      types("cli/commands/task.ts"),
      any("cli/usage.ts", ["CliUsageError"]),
      any("task/index.ts"),
      any("task/operations.ts", ["observeTaskDetails"]),
      any("task/context.ts", ["resolveTaskNamespaceContext", "writeTaskNamespaceContext"]),
      any("task/mutation.ts"),
      types("world.ts"),
      any("akuma/requests.ts", ["injectedBodyRequests", "requestBodyTask"]),
    ],
  },
  {
    source: "cli/draft.ts",
    allow: [any("coordination/durable-file.ts"), types("cli/result.ts"), types("world.ts")],
  },
  { source: "cli/render/akuma-tool-command.ts", allow: [] },
  { source: "cli/render/akuma-tool.ts", allow: [types("akuma/index.ts"), any("cli/render/akuma-tool-command.ts")] },
  {
    source: "cli/render/akuma.ts",
    allow: [
      any("akuma/index.ts", ["defaultWaitComplete"]),
      types("akuma/index.ts"),
      types("index.ts"),
      types("cli/commands/akuma-invoke.ts"),
      types("cli/parse.ts"),
      any("cli/render/akuma-tool.ts"),
      any("cli/render/terminal.ts", [
        "TextRenderContext",
        "displayColumns",
        "renderBoundedTextBlock",
        "safeText",
        "truncateMiddleDisplayText",
      ]),
      any("cli/render/akuma-activity.ts"),
    ],
  },
  {
    source: "cli/render/akuma-activity.ts",
    allow: [
      any("akuma/index.ts", ["defaultWaitComplete"]),
      types("akuma/index.ts"),
      types("index.ts"),
      types("cli/commands/akuma-invoke.ts"),
      types("cli/parse.ts"),
      any("cli/render/akuma-tool.ts"),
      any("cli/render/terminal.ts", [
        "TextRenderContext",
        "displayColumns",
        "renderBoundedTextBlock",
        "safeText",
        "truncateMiddleDisplayText",
      ]),
    ],
  },
  {
    source: "cli/render/catalog.ts",
    allow: [types("index.ts"), any("cli/render/contract-observation.ts"), any("cli/render/terminal.ts", ["safeText"])],
  },
  { source: "cli/render/contract-observation.ts", allow: [types("index.ts")] },
  {
    source: "cli/main.ts",
    allow: [any("cli/parse.ts"), any("cli/runtime.ts")],
  },
  {
    source: "cli/parse.ts",
    allow: [
      any("cli/commands/akuma.ts"),
      any("cli/commands/contract.ts"),
      any("cli/commands/install.ts"),
      any("cli/commands/task.ts"),
      any("cli/usage.ts"),
    ],
  },
  {
    source: "cli/coordinates.ts",
    allow: [any("cli/parse.ts"), any("library/repo.ts", ["NoGitWorldError", "Repo"]), any("world.ts")],
  },
  {
    source: "cli/runtime.ts",
    allow: [
      types("cli/commands/akuma.ts"),
      types("cli/commands/akuma-invoke.ts"),
      types("cli/commands/install.ts"),
      types("cli/commands/task-invoke.ts"),
      types("cli/parse.ts"),
      types("cli/result.ts"),
      types("settings.ts"),
      any("cli/commands/akuma.ts", ["isParsedAkumaCommand"]),
      any("cli/commands/install.ts"),
      any("cli/draft.ts"),
      any("cli/invoke.ts"),
      any("cli/parse.ts", ["CliUsageError"]),
      any("cli/render/**"),
      any("library/address.ts"),
    ],
  },
  {
    source: "cli/commands/amend.ts",
    allow: [types("index.ts"), types("cli/commands/contract.ts", ["ParsedAmend"]), any("cli/selectors.ts")],
  },
  {
    source: "cli/commands/bind.ts",
    allow: [
      any("index.ts"),
      any("library/contract.ts", ["bindFromCli"]),
      types("cli/commands/contract.ts", ["ParsedBind"]),
      any("cli/selectors.ts"),
    ],
  },
  {
    source: "cli/commands/contract.ts",
    allow: [
      any("akuma/identity.ts", ["archetypeName"]),
      types("library/catalog.ts", ["CatalogQuery"]),
      any("cli/usage.ts", ["CliUsageError", "usageLine"]),
    ],
  },
  {
    source: "cli/commands/contract-invoke.ts",
    allow: [
      types("index.ts"),
      types("cli/parse.ts"),
      types("cli/result.ts"),
      types("cli/selectors.ts"),
      types("library/configuration.ts"),
      types("library/repo.ts"),
      types("settings.ts"),
      types("world.ts"),
      any("cli/accepted.ts"),
      any("cli/actor.ts"),
      any("cli/commands/amend.ts"),
      any("cli/commands/bind.ts"),
      any("cli/draft.ts"),
      any("cli/selectors.ts"),
      any("cli/usage.ts"),
      any("library/configuration.ts"),
      any("library/keiyaku.ts"),
    ],
  },
  {
    source: "cli/invoke.ts",
    allow: [
      types("index.ts"),
      types("kanshi/index.ts"),
      types("library/repo.ts"),
      types("world.ts"),
      types("cli/commands/akuma.ts"),
      types("cli/commands/akuma-invoke.ts"),
      types("cli/commands/install.ts"),
      types("cli/commands/task-invoke.ts"),
      types("cli/result.ts"),
      any("cli/accepted.ts"),
      any("cli/actor.ts"),
      any("cli/commands/**"),
      any("cli/square-edge.ts"),
      any("akuma/publication.ts"),
      any("cli/coordinates.ts"),
      any("cli/draft.ts"),
      any("cli/parse.ts"),
      any("cli/selectors.ts"),
      any("cli/usage.ts"),
      any("akuma/requests.ts"),
      any("kanshi/index.ts"),
      any("library/address.ts"),
      any("library/configuration.ts"),
      any("library/keiyaku.ts"),
      any("settings.ts"),
    ],
  },
  {
    source: "cli/commands/status-set.ts",
    allow: [
      types("cli/result.ts"),
      any("cli/parse.ts"),
      any("cli/selectors.ts"),
      any("cli/commands/akuma-invoke.ts"),
      any("kanshi/index.ts"),
      any("library/address.ts"),
      types("library/repo.ts"),
      types("world.ts"),
    ],
  },
  {
    source: "cli/square-edge.ts",
    allow: [any("@astrosheep/square"), any("akuma/identity.ts"), any("akuma/publication.ts"), types("world.ts")],
  },
  {
    source: "scripts/architecture/**",
    allow: [
      types("scripts/architecture/engine.ts"),
      any("scripts/architecture/engine-parser.ts"),
      any("scripts/architecture/policy-helpers.ts"),
      any("scripts/architecture/policy.ts"),
      any("scripts/architecture/policy-akuma.ts"),
      any("scripts/architecture/policy-cli.ts"),
      any("scripts/architecture/policy-core.ts"),
      any("scripts/architecture/policy-foundation.ts"),
      any("scripts/architecture/policy-git.ts"),
      any("scripts/architecture/policy-protocol.ts"),
      any("scripts/architecture/policy-runtime-library.ts"),
      any("scripts/architecture/policy-task-kanshi.ts"),
    ],
  },
  {
    source: "scripts/check-architecture.ts",
    allow: [any("scripts/architecture/engine.ts"), any("scripts/architecture/policy.ts")],
  },
  { source: "scripts/model-impact/**", allow: [types("scripts/model-impact/engine.ts")] },
  {
    source: "cli/accepted.ts",
    allow: [any("index.ts"), types("library/region.ts"), any("cli/result.ts")],
  },
  { source: "cli/actor.ts", allow: [types("index.ts")] },
  {
    source: "cli/commands/nuke.ts",
    allow: [any("index.ts"), types("world.ts"), any("cli/parse.ts"), types("cli/result.ts")],
  },
  { source: "cli/index.ts", allow: [any("cli/main.ts")] },
  {
    source: "cli/render/audit.ts",
    allow: [
      types("index.ts"),
      types("cli/result.ts"),
      any("cli/render/receipt.ts"),
      any("cli/render/refusal.ts"),
      any("cli/render/terminal.ts"),
    ],
  },
  {
    source: "cli/render/contract-history.ts",
    allow: [types("index.ts"), any("cli/render/receipt.ts", ["receiptPayload"])],
  },
  { source: "cli/render/board.ts", allow: [types("cli/result.ts")] },
  {
    source: "cli/render/contract.ts",
    allow: [
      types("index.ts"),
      types("cli/result.ts"),
      any("cli/render/audit.ts"),
      any("cli/render/receipt.ts"),
      any("cli/render/terminal.ts"),
      any("cli/render/contract-history.ts"),
    ],
  },
  {
    source: "cli/render/kanshi.ts",
    allow: [
      types("index.ts"),
      types("kanshi/index.ts"),
      any("kanshi/fleet.ts"),
      any("cli/render/contract-observation.ts"),
      any("cli/render/terminal.ts"),
    ],
  },
  { source: "cli/render/nuke.ts", allow: [types("index.ts")] },
  {
    source: "cli/render/receipt.ts",
    allow: [types("index.ts"), types("cli/result.ts"), any("cli/render/terminal.ts")],
  },
  {
    source: "cli/render/refusal.ts",
    allow: [types("index.ts"), types("cli/result.ts"), any("cli/render/terminal.ts")],
  },
  { source: "cli/render/region.ts", allow: [types("kanshi/index.ts")] },
  { source: "cli/render/settings.ts", allow: [types("settings.ts")] },
  {
    source: "cli/render/task.ts",
    allow: [
      types("task/index.ts"),
      types("cli/commands/task-invoke.ts"),
      types("cli/commands/task.ts"),
      any("cli/render/receipt.ts"),
      any("cli/render/terminal.ts"),
    ],
  },
  { source: "cli/render/terminal.ts", allow: [] },
  {
    source: "cli/render/text.ts",
    allow: [
      types("cli/result.ts"),
      any("cli/render/board.ts"),
      any("cli/render/contract.ts"),
      any("cli/render/kanshi.ts"),
      any("cli/render/refusal.ts"),
      types("cli/render/terminal.ts"),
      any("cli/render/catalog.ts"),
      any("cli/render/nuke.ts"),
      any("cli/render/region.ts"),
      any("cli/render/status-set.ts"),
    ],
  },
  {
    source: "cli/render/status-set.ts",
    allow: [
      types("cli/result.ts"),
      any("cli/render/akuma.ts"),
      any("cli/render/kanshi.ts"),
      types("cli/render/terminal.ts"),
    ],
  },
  {
    source: "cli/result.ts",
    allow: [types("index.ts"), types("kanshi/index.ts"), types("library/region.ts")],
  },
  {
    source: "cli/selectors.ts",
    allow: [any("identity/coordinates.ts"), any("index.ts"), types("kanshi/index.ts"), any("cli/parse.ts")],
  },
  { source: "cli/usage.ts", allow: [] },
  {
    source: "scripts/model-change-impact.ts",
    allow: [any("scripts/model-impact/engine.ts"), any("scripts/model-impact/policy.ts")],
  },
];
