import type { ArchitecturePolicy } from "./engine.js";

const any = (target: string, symbols?: readonly string[]) => symbols ? { target, symbols } : { target };
const types = (target: string) => ({ target, mode: "type-only" as const });

export const KEIYAKU_ARCHITECTURE_POLICY = {
  zones: [
    { source: "core/facts/types.ts", allow: [] },
    { source: "core/facts/errors.ts", allow: [] },
    { source: "core/facts/codec.ts", allow: [any("core/facts/errors.ts"), any("core/facts/types.ts"), any("core/subject.ts", ["parseDependencyKeySet"])] },
    {
      source: "core/facts/fold.ts",
      allow: [
        any("core/facts/eligibility.ts", ["samePrerequisites"]),
        any("core/facts/errors.ts"),
        any("core/facts/gate.ts"),
        types("core/facts/types.ts"),
      ],
    },
    { source: "core/facts/gate.ts", allow: [any("core/subject.ts"), types("core/facts/types.ts")] },
    { source: "core/subject.ts", allow: [any("core/facts/errors.ts"), any("core/facts/types.ts")] },
    { source: "core/facts/eligibility.ts", allow: [any("core/facts/observation.ts"), types("core/facts/offer.ts"), types("core/facts/types.ts")] },
    { source: "core/facts/offer.ts", allow: [types("core/facts/types.ts")] },
    { source: "core/facts/observation.ts", allow: [types("core/facts/types.ts")] },
    {
      source: "core/decide.ts",
      allow: [types("core/facts/observation.ts"), types("core/facts/offer.ts"), types("core/facts/types.ts")],
    },
    {
      source: "core/verbs/**",
      allow: [
        types("core/decide.ts"),
        types("core/facts/offer.ts"),
        any("core/facts/eligibility.ts", ["placeEligibleBounds", "prerequisiteStatus", "prerequisitesReach", "samePrerequisites"]),
        any("core/facts/gate.ts"),
        any("core/facts/observation.ts", ["activeContract", "contractState", "documentIsCurrent"]),
        types("core/facts/types.ts"),
      ],
    },
    { source: "carrier/identity.ts", allow: [any("core/facts/types.ts")] },
    { source: "carrier/repository.ts", allow: [any("carrier/identity.ts"), any("core/facts/errors.ts")] },
    {
      source: "carrier/admission.ts",
      allow: [
        any("carrier/identity.ts"),
        types("carrier/observe.ts"),
        any("carrier/repository.ts"),
        any("core/facts/codec.ts"),
        types("core/facts/offer.ts"),
        types("core/facts/types.ts"),
      ],
    },
    {
      source: "carrier/observe.ts",
      allow: [
        any("carrier/identity.ts"),
        any("carrier/repository.ts"),
        any("core/facts/errors.ts"),
        any("core/facts/codec.ts"),
        any("core/facts/fold.ts"),
        types("core/facts/observation.ts"),
        types("core/facts/types.ts"),
      ],
    },
    {
      source: "carrier/delivery.ts",
      allow: [
        any("carrier/identity.ts"),
        any("carrier/reconcile.ts"),
        any("carrier/repository.ts"),
        types("core/decide.ts"),
        types("core/facts/types.ts"),
      ],
    },
    {
      source: "carrier/reconcile.ts",
      allow: [any("carrier/identity.ts"), any("carrier/repository.ts"), any("core/facts/types.ts")],
    },
    {
      source: "carrier/verification.ts",
      allow: [any("carrier/identity.ts"), any("carrier/repository.ts"), any("core/facts/errors.ts"), types("core/facts/types.ts")],
    },
    {
      source: "protocol/attempt.ts",
      allow: [
        any("carrier/admission.ts"),
        any("carrier/observe.ts"),
        any("carrier/repository.ts", ["CARRIER_REF", "GitRepository", "readRef"]),
        types("carrier/repository.ts"),
        types("core/decide.ts"),
        any("core/facts/codec.ts"),
        any("core/facts/errors.ts"),
        any("core/facts/fold.ts", ["foldJournal"]),
        any("core/facts/observation.ts"),
        types("core/facts/offer.ts"),
        types("core/facts/types.ts"),
      ],
    },
    {
      source: "protocol/run.ts",
      allow: [
        any("carrier/observe.ts"),
        types("carrier/repository.ts"),
        types("core/decide.ts"),
        types("core/facts/types.ts"),
        any("protocol/attempt.ts"),
      ],
    },
    {
      source: "protocol/intent.ts",
      allow: [
        any("carrier/observe.ts"),
        any("carrier/verification.ts", ["materializeVerificationCandidate"]),
        types("carrier/verification.ts"),
        types("carrier/repository.ts"),
        types("core/decide.ts"),
        any("core/facts/eligibility.ts"),
        any("core/facts/types.ts"),
        any("core/subject.ts", ["dependencyKeySet"]),
        any("core/verbs/placement.ts"),
        any("core/verbs/attestation.ts"),
        any("protocol/run.ts"),
        types("verification/producer.ts"),
        types("verification/types.ts"),
      ],
    },
    {
      source: "protocol/operations.ts",
      allow: [
        any("carrier/delivery.ts"),
        any("carrier/identity.ts"),
        any("carrier/observe.ts"),
        any("carrier/reconcile.ts"),
        any("carrier/repository.ts"),
        any("carrier/verification.ts", ["readDeliveryDiff"]),
        types("carrier/verification.ts"),
        any("core/facts/observation.ts", ["contractState", "documentIsCurrent"]),
        any("core/facts/types.ts", ["gate"]),
        types("core/facts/types.ts"),
        any("core/subject.ts", ["dependencyKeySet"]),
        any("core/verbs/abandon.ts"),
        any("core/verbs/amend.ts"),
        any("core/verbs/arc.ts"),
        any("core/verbs/bind.ts"),
        any("core/verbs/deliver.ts"),
        types("core/verbs/placement.ts"),
        any("core/verbs/attestation.ts"),
        any("protocol/intent.ts"),
        any("protocol/attempt.ts"),
        any("protocol/read/audit.ts"),
        any("protocol/read/documents.ts"),
        any("protocol/read/status.ts"),
        types("protocol/run.ts"),
        any("verification/producer.ts"),
        types("verification/types.ts"),
      ],
    },
    {
      source: "protocol/read/**",
      allow: [
        any("carrier/observe.ts"),
        any("carrier/reconcile.ts", ["deliveryWorktreePath"]),
        types("carrier/repository.ts"),
        any("core/facts/gate.ts", ["latestCurrentAttestations"]),
        any("core/facts/types.ts", ["ContractId", "ContractState", "Gate", "gate"]),
        types("core/facts/types.ts"),
      ],
    },
    { source: "runtime/proc/**", allow: [] },
    { source: "verification/types.ts", allow: [types("core/facts/types.ts")] },
    {
      source: "verification/producer.ts",
      allow: [
        types("core/facts/types.ts"),
        any("runtime/proc/run.ts"),
        types("verification/types.ts"),
      ],
    },
    {
      source: "library/keiyaku.ts",
      allow: [
        any("body/amend.ts"),
        any("body/arc.ts"),
        any("body/decode.ts"),
        any("body/region.ts"),
        any("body/render.ts"),
        types("body/types.ts"),
        any("core/facts/errors.ts"),
        any("core/facts/types.ts"),
        any("protocol/operations.ts"),
      ],
    },
    { source: "library/**", allow: [] },
    {
      source: "index.ts",
      allow: [any("library/keiyaku.ts")],
    },
    { source: "markdown/**", allow: [any("markdown/lex.ts"), any("markdown/types.ts")] },
    {
      source: "body/amend.ts",
      allow: [
        any("body/region.ts"), any("body/render.ts"), any("body/shape.ts"), types("body/types.ts"),
        any("body/verification.ts"), any("markdown/parse.ts"), any("markdown/query.ts"), types("markdown/types.ts"),
        types("verification/types.ts"),
      ],
    },
    {
      source: "body/**",
      allow: [
        any("body/keys.ts"),
        any("body/region.ts"),
        any("body/shape.ts"),
        types("body/types.ts"),
        any("body/verification.ts"),
        any("markdown/parse.ts"),
        any("markdown/query.ts"),
        types("markdown/types.ts"),
        any("core/facts/types.ts"),
        types("verification/types.ts"),
      ],
    },
    {
      source: "cli/**",
      allow: [
        any("index.ts"),
        any("cli/accepted.ts"),
        any("cli/actor.ts"),
        any("cli/commands/**"),
        any("cli/invoke.ts"),
        any("cli/main.ts"),
        any("cli/parse.ts"),
        any("cli/render/**"),
        types("cli/result.ts"),
        any("cli/selectors.ts"),
        any("cli/settings.ts"),
      ],
    },
    { source: "scripts/architecture/**", allow: [types("scripts/architecture/engine.ts")] },
    {
      source: "scripts/check-architecture.ts",
      allow: [any("scripts/architecture/engine.ts"), any("scripts/architecture/policy.ts")],
    },
    { source: "scripts/model-impact/**", allow: [types("scripts/model-impact/engine.ts")] },
    {
      source: "scripts/model-change-impact.ts",
      allow: [any("scripts/model-impact/engine.ts"), any("scripts/model-impact/policy.ts")],
    },
  ],
  sensitiveImports: [
    { module: "node:module", owners: [] },
    { module: "module", owners: [] },
    {
      module: "node:child_process",
      owners: [
        { source: "carrier/repository.ts", symbols: ["execFileSync"] },
        { source: "runtime/proc/**", symbols: ["spawn"] },
        { source: "scripts/model-change-impact.ts", symbols: ["execFileSync"] },
      ],
    },
    { module: "child_process", owners: [] },
    {
      module: "node:fs",
      owners: [
        { source: "scripts/check-architecture.ts", symbols: ["readFileSync", "readdirSync"] },
        { source: "scripts/model-change-impact.ts", symbols: ["readFileSync", "readdirSync"] },
        { source: "cli/invoke.ts", symbols: ["readFileSync"] },
        { source: "cli/settings.ts", symbols: ["readFileSync"] },
        { source: "carrier/reconcile.ts", symbols: ["existsSync", "mkdirSync", "realpathSync"] },
        { source: "carrier/delivery.ts", symbols: ["existsSync", "mkdtempSync", "rmSync"] },
      ],
    },
    { module: "fs", owners: [] },
    { module: "node:fs/promises", owners: [] },
    { module: "fs/promises", owners: [] },
    {
      module: "node:crypto",
      owners: [
        { source: "carrier/verification.ts", symbols: ["randomBytes"] },
        { source: "carrier/identity.ts", symbols: ["randomBytes"] },
        { source: "protocol/intent.ts", symbols: ["randomBytes"] },
        { source: "body/keys.ts", symbols: ["createHash"] },
      ],
    },
    { module: "crypto", owners: [] },
  ],
  forbiddenModules: [
    "better-sqlite3",
    "sqlite3",
    "node:sqlite",
  ],
  capabilityRules: [
    { capability: "dynamic-import-nonliteral", owners: [] },
    { capability: "eval", owners: [] },
    { capability: "function-constructor", owners: [] },
    { capability: "math-random", owners: [] },
    { capability: "module-mutable-state", owners: [] },
    { capability: "date-now", owners: ["carrier/identity.ts", "protocol/intent.ts"] },
    { capability: "new-date-current", owners: ["protocol/operations.ts"] },
    { capability: "process-argv", owners: ["cli/main.ts", "cli/index.ts", "scripts/check-architecture.ts", "scripts/model-change-impact.ts"] },
    { capability: "process-cwd", owners: ["carrier/repository.ts", "library/keiyaku.ts", "scripts/check-architecture.ts", "scripts/model-change-impact.ts"] },
    { capability: "process-environment", owners: ["cli/invoke.ts", "carrier/repository.ts", "protocol/operations.ts"] },
    { capability: "process-output", owners: ["cli/main.ts", "cli/index.ts", "scripts/check-architecture.ts", "scripts/model-change-impact.ts"] },
    { capability: "process-pid", owners: [] },
    { capability: "require", owners: [] },
    { capability: "type-error-construction", owners: ["body/**", "cli/actor.ts", "library/keiyaku.ts"] },
  ],
  forbiddenFileNames: [
    "approval-preparation.ts",
    "claim.ts",
    "forfeit.ts",
    "open.ts",
    "petition-preparation.ts",
    "petition.ts",
    "pipeline.ts",
    "renew.ts",
    "seal.ts",
  ],
  forbiddenDeclarations: [
    /(?:Open|Seal|Renew|Petition|Claim|Forfeit)(?:Data|Entry|Input|Refusal|Decision|Offer|State|Result)$/,
  ],
  verbDirectory: "core/verbs/",
} as const satisfies ArchitecturePolicy;
