import { any, factErrors, factTypes, gitRepository, types } from "./policy-helpers.js";
export const taskKanshiZones = [
  {
    source: "task/catalog.ts",
    allow: [any("task/board.ts"), any("task/identity.ts"), any("task/store.ts"), types("world.ts")],
  },
  { source: "markdown/**", allow: [any("markdown/lex.ts"), any("markdown/types.ts"), any("markdown/diff.ts")] },
  { source: "task/identity.ts", allow: [any("identity/coordinates.ts"), any("identity/normalize.ts")] },
  { source: "task/context.ts", allow: [any("coordination/durable-file.ts"), any("identity/normalize.ts")] },
  { source: "task/document.ts", allow: [any("task/identity.ts")] },
  { source: "task/board.ts", allow: [types("task/document.ts"), any("task/identity.ts")] },
  {
    source: "task/store.ts",
    allow: [
      types("world.ts"),
      any("coordination/sqlite-transaction-lock.ts"),
      any("task/board.ts"),
      any("task/document.ts"),
      any("task/identity.ts"),
    ],
  },
  { source: "task/query.ts", allow: [any("task/board.ts"), types("task/document.ts"), any("task/identity.ts")] },
  {
    source: "task/operations.ts",
    allow: [
      types("world.ts"),
      any("markdown/diff.ts"),
      any("task/context.ts"),
      any("task/board.ts"),
      any("task/document.ts"),
      any("task/identity.ts"),
      any("task/query.ts"),
      any("task/store.ts"),
    ],
  },
  {
    source: "task/compose-parser.ts",
    allow: [any("task/identity.ts"), types("task/operations.ts")],
  },
  {
    source: "task/compose-language.ts",
    allow: [
      any("task/compose-parser.ts"),
      any("task/board.ts"),
      any("task/document.ts"),
      any("task/identity.ts"),
      any("task/operations.ts"),
    ],
  },
  {
    source: "task/compose.ts",
    allow: [
      types("world.ts"),
      any("markdown/diff.ts"),
      any("task/compose-language.ts"),
      any("task/document.ts"),
      types("task/identity.ts"),
      any("task/operations.ts"),
      any("task/store.ts"),
    ],
  },
  {
    source: "task/input.ts",
    allow: [any("task/document.ts"), any("task/identity.ts"), types("task/operations.ts"), any("task/query.ts")],
  },
  {
    source: "task/mutation.ts",
    allow: [
      types("world.ts"),
      types("task/compose.ts"),
      any("task/input.ts"),
      any("task/index.ts"),
      any("task/identity.ts", ["parseTaskId", "TaskId"]),
      types("task/operations.ts"),
      any("task/mutation-result.ts", ["TaskMutationExecutionResult", "isTaskMutationExecutionResult"]),
      any("akuma/request-rendezvous.ts", ["requestBodyCommand"]),
      any("akuma/request-wire.ts", ["eraseRequestCommand", "ErasedRequestCommand", "RequestCommand"]),
    ],
  },
  {
    source: "task/mutation-result.ts",
    allow: [
      any("task/input.ts", ["taskId"]),
      any("task/identity.ts", ["parseTaskId", "TaskId"]),
      types("task/compose.ts", ["TaskCompositionResult"]),
      types("task/operations.ts", ["TaskBatchResult", "TaskMutationResult", "TaskUpdateResult"]),
    ],
  },
  {
    source: "task/index.ts",
    allow: [
      types("world.ts"),
      any("task/board.ts"),
      any("task/compose.ts"),
      any("task/document.ts"),
      any("task/identity.ts"),
      any("task/input.ts"),
      any("task/operations.ts"),
      any("task/query.ts"),
      any("task/store.ts"),
    ],
  },
  {
    source: "settlement/fence.ts",
    allow: [
      any("coordination/sqlite-transaction-lock.ts"),
      any("git/repository.ts"),
      gitRepository,
      any("task/identity.ts", ["parseTaskId", "TaskId"]),
    ],
  },
  {
    source: "settlement/holder.ts",
    allow: [
      factErrors,
      types("core/facts/offer.ts"),
      factTypes,
      types("git/observe.ts", ["GitDecisionObservation"]),
      any("git/private-state-seat.ts"),
      any("git/read-observation.ts"),
      any("git/repository.ts"),
      gitRepository,
      any("settlement/fence.ts"),
      any("task/identity.ts"),
    ],
  },
  {
    source: "settlement/settle.ts",
    allow: [
      any("world.ts"),
      any("git/observe.ts"),
      any("git/private-state-seat.ts"),
      any("git/read-observation.ts"),
      types("git/reconcile.ts"),
      gitRepository,
      factTypes,
      any("settlement/fence.ts"),
      any("settlement/holder.ts"),
      any("task/context.ts"),
      any("task/operations.ts"),
      types("task/identity.ts"),
      types("task/store.ts"),
    ],
  },
  {
    source: "kanshi/read.ts",
    allow: [
      types("world.ts"),
      any("akuma/index.ts"),
      any("alias/index.ts", ["AliasBinding", "readAliases"]),
      any("dispatch/index.ts", ["Dispatch", "readDispatchesAt"]),
      any("git/read-observation.ts", ["GitReadObservation", "withGitDecodeChannel", "withGitReadObservation"]),
      any("kanshi/**"),
      any("library/region.ts", ["readRegionDeclarations", "validateRegionPatterns"]),
      any("core/facts/types.ts", ["contractId"]),
      types("library/contract.ts"),
      any("library/repo.ts", ["Repo", "scopeForRepo"]),
      any("protocol/read/status.ts", ["readContractBoard"]),
      any("protocol/read/observation.ts", ["observeCurrentPhysicalIssue"]),
      any("protocol/read/documents.ts", ["readDocuments"]),
      any("settlement/holder.ts", ["TaskHolderProjection", "readTaskHolderProjectionAt"]),
      any("settlement/settle.ts", ["contractNamespace"]),
      types("task/index.ts"),
      any("task/operations.ts", ["observeTaskBoard"]),
    ],
  },
  {
    source: "kanshi/report.ts",
    allow: [
      types("world.ts"),
      types("akuma/index.ts"),
      types("identity/selector.ts"),
      types("library/contract.ts"),
      types("library/region.ts", ["RegionOverlap"]),
      types("protocol/read/observation.ts", ["CurrentPhysicalIssue"]),
      types("task/index.ts"),
    ],
  },
  { source: "kanshi/fleet.ts", allow: [types("kanshi/report.ts", ["AkumaKanshiRow"])] },
  { source: "kanshi/select.ts", allow: [types("kanshi/report.ts"), any("library/region.ts", ["regionOverlaps"])] },
  { source: "kanshi/**", allow: [any("index.ts"), any("kanshi/**"), any("task/index.ts")] },
  {
    source: "body/amend.ts",
    allow: [
      any("body/region.ts"),
      any("body/render.ts"),
      any("body/shape.ts"),
      types("body/types.ts"),
      any("body/verification.ts"),
      any("markdown/parse.ts"),
      any("markdown/query.ts"),
      types("markdown/types.ts"),
      types("verification/declaration.ts"),
    ],
  },
  {
    source: "body/**",
    allow: [
      any("body/envelope.ts"),
      any("body/keys.ts"),
      any("body/region.ts"),
      any("body/shape.ts"),
      types("body/types.ts"),
      any("body/verification.ts"),
      any("markdown/parse.ts"),
      any("markdown/query.ts"),
      types("markdown/types.ts"),
      factTypes,
      any("duration.ts"),
      types("verification/declaration.ts"),
    ],
  },
];
